### PR TITLE
avoid null-deref of `peeraddr` depending on the environment

### PR DESCRIPTION
**Pull request by kazuho**
The regression that we caused with #2493 is that the code no longer compiles on macOS (or other operating systems that do not have `accept4`). Note also that on those platforms, `peeraddr` is NULL.

This PR addresses the problem by adding a NULL-check.

### CODE REVIEW

**Comment by kazuho** [comment]
@jdamato-fsly @syohex I would appreciate it if you could have a look.

**Review by syohex — APPROVED** [review]
Looks good

**Review by jdamato-fsly — APPROVED** [review]
Thanks and sorry for the trouble :)

**Comment by kazuho** [comment]
Thank you for the reviews.

Regarding this issue, I would blame us not having CI setup for various platforms. Hopefully we'd have that as we move to GitHub Actions.

**Pull request merged**
