### PR TITLE
log protocol-specific values

### PR DESCRIPTION
**Pull request by kazuho**
e.g. TLS ciphersuite, HTTP/2 stream ID.

still wip

part of #36, implements #149

### CODE REVIEW

**Comment by kazuho** [comment]
As of d91b12c, following directives are supported:
* `%{http2.stream-id}x` - logs the stream id
* `%{http2.priority.received}x` - values of exclusive, parent, weight concatenated with `:`
* `%{http2.priority.received.exclusive}x` - `1` if exclusive bit was set in the last priority information received for the request, or `0` if otherwise
* `%{http2.priority.received.parent}x` - last parent stream ID designated by the client
* `%{http2.priority.received.weight}x` - last stream weight designated by the client

**Comment by kazuho** [comment]
In a9d3228 added:
* `%{ssl.protocol-version}x`
* `%{ssl.session-reused}x`
* `%{ssl.cipher}x`
* `%{ssl.cipher-bits}x`

**Comment by kazuho** [comment]
In 5d4333b added `%{connection-id}x` that emits a monotonously increasing ID for every new TCP / TLS connection.

**Comment by Tintinabula** [comment]
Thank you for the additional logging variables. The cipher logging allowed us to take survey of clients and remove unused ssl ciphers. The following table shows the most used ciphers by client connection for Thursday, Feb 25. SHA1 ciphers could be removed since the logs proved SHA1 was not being used by our clients.

```
SSL Ciphers (2016-02-25)
^^^^^^^^^^^^^^^^^^^^^^^^^
995894 ECDHE-RSA-AES256-GCM-SHA384
579730 ECDHE-RSA-AES128-GCM-SHA256
398709 ECDHE-RSA-CHACHA20-POLY1305
 70723 ECDHE-RSA-AES256-SHA384
  2411 ECDHE-RSA-AES128-SHA256
```

**Comment by kazuho** [comment]
@Tintinabula Thank you for the stats. Interesting!

**Pull request merged**
