### PR TITLE
Add fail handler

### PR DESCRIPTION
**Pull request by fbbdev**
Fail handler sends an error response with the specified status. This is useful to prevent clients from accessing non-existent hosts or protected paths.

### CODE REVIEW

**Comment by fbbdev** [comment]
# Examples

## Prevent access to non-existent hosts
```yaml
hosts:
  default:
    paths:
      /:
        fail: 403
  "example.com:80":
    paths:
      /:
        file.dir: /path/to/doc-root
```

## Hide details
```yaml
hosts:
  default:
    paths:
      /:
        file.dir: /path/to/doc-root
        file.index: [ 'foo.html' ]
      /foo.html:
        fail: 404
```

**Comment by kazuho** [comment]
Thank you for the PR!  And thank you for including documentation and tests.

Please let me consider how I should merge this.

**Comment by kazuho** [comment]
Thank you for waiting long.

To keep the core small (and to provide maximum flexibility), I have decided not to merge this PR but instead to encourage people to use scripting with mruby for this kind of requirements.

Using the mruby handler, you can write like:

```
paths:
  /:
    mruby.handler: |
      H2O.return 403, "Access Forbidden", "I will never show you this!"
```

And once #471 gets merged, it would become possible to send a file with an arbitrary status code (using mruby).

**Comment by fbbdev** [comment]
Thank you.

**Pull request closed without merging**
