### PR TITLE
I packaged h2o rudimentary.

### PR DESCRIPTION
**Pull request by lkwg82**
This is meant as a begin. I dont have a lot practice with packaging. So there might be some mistakes.

Beside it is installable and runs.

Hope you like it and some other people join to make it better!

Cheers Lars

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  It is great have H2O as an .deb!

However, I believe that including it within the repository of H2O is not a good idea since it complicates the release engineering.

I believe that the release process of H2O should concentrate on creating a tarball, and then packaging should be done as a separate process for each package manager independently; and that that is the way packaging is usually done.

**Comment by lkwg82** [comment]
Maybe a separate packaging repo should fill that gap.

**Comment by kazuho** [comment]
@lkwg82 Agreed.  Do you want me to setup a repository under github.com/h2o?

**Comment by lkwg82** [comment]
this would be fine

**Comment by kazuho** [comment]
@lkwg82 Great!  Created https://github.com/h2o/h2o.deb and sent invitation.  Please feel free to push and release code.

**Comment by vincentbernat** [comment]
@lkwg82 Any progress on this? After a very quick look, your packaging is missing logrotate handling and installation of an init script (and eventually a systemd unit file).

**Comment by szepeviktor** [comment]
libwslay is a dependency and it needs to be packaged as well.
I don't know how to package a lib properly (but I have a [repo](http://szepeviktor.github.io/debian/))
I think initially a very simple h2o Debian package is better than compiling from source

**Comment by szepeviktor** [comment]
One must decide: LibreSSL or OpenSSL.
My choice is the former.

**Comment by vincentbernat** [comment]
@szepeviktor I thought I had already packaged libwslay but that's not the case. I should be able to push a package shortly in Sid (it should be easy to backport it to earlier distributions). Also, LibreSSL is not in Debian and isn't likely to happen soon (due to lack of interest).

**Comment by lkwg82** [comment]
@vincentbernat

Sorry I missed ur question. Currently I do not plan to continue. This state is free to take over!

Cheers Lars

**Comment by guilhem** [comment]
JFYI, I manage to build h2o and create a PPA: https://launchpad.net/~h2o-maintainers/+archive/ubuntu/stable

If anyone want helping me, let's ask for on on https://launchpad.net/~h2o-maintainers ;)

My main problem was git import. As there is submodules, it's impossible to auto-import git repo on bzr launchpad :/

**Comment by szepeviktor** [comment]
@guilhem  Please be advised that lib-h2o could be a separate binary package.

**Comment by guilhem** [comment]
@szepeviktor nice to know, I have to work more on it.

For the moment I also created a docker image to use h2o https://hub.docker.com/r/themecloud/h2o/

It can be easily use as `FROM themecloud/h2o`.

I also have to add tags etc.

**Comment by lkwg82** [comment]
what is the status of this pr?

**Comment by kazuho** [comment]
Let's close this.

My understanding is that for Ubuntu @guilhem has created https://launchpad.net/%7Eh2o-maintainers/+archive/ubuntu/stable.

@guilhem are you still maintaining the PPA?  If yes, it would be great if you could update it to 1.7.0.

**Pull request closed without merging**
