### PR TITLE
add knob to configure h3-idle-timeout

### PR DESCRIPTION
**Pull request by kazuho**
`http3-idle-timeout` works exactly like `http2-idle-timeout`, with the exception that it applies to http/3. Note that the default is 30 seconds, as we do not expect NAT entries to survive longer than that.

### CODE REVIEW

**Comment by kazuho** [comment]
@janaiyengar Does the default timeout of 30 seconds (which BTW is the default we have in `quicly_spec_context`) make sense to you?

**Comment by janaiyengar** [comment]
@kazuho : 30 seconds makes sense to me as a default.

**Comment by kazuho** [comment]
@janaiyengar Thank you for the confirmation.

**Comment by kazuho** [comment]
@hfujita I'm sending you a review request to let you know that we are adding this knob, though please do not feel obliged to do a thorough review. Your review is always helpful, but I think there's nothing controversial in this PR.

**Comment by hfujita** [comment]
@kazuho Thanks. In fact these review requests are pretty useful for me to catch up with the latest movement in the code.

I just noticed that we haven't added a documentation for http3 directives (including `http3-graceful-shutdown-timeout` in #2422). Are we going to do that later, once http3 support becomes more stabilized?

**Comment by kazuho** [comment]
Re documentation, good point. Let's handle that separately, as I think the work is going to be more than just writing down the configuration directive; we need a page dedicated to http3, much like we have for http1 and http2. Added a note to #2414.

**Pull request merged**
