### PR TITLE
keep mruby's PATH_INFO undecoded

### PR DESCRIPTION
**Pull request by i110**
Currently mruby env's `PATH_INFO` value is url-decoded. For example, if we access to `/foo%20bar`, `env['PATH_INFO']` will be `/foo bar` .

Facts:
- Popular Ruby application servers keeps it undecoded
  - unicorn / thin / puma / webrick
- Rack specification is very ambiguous (says `This value may be percent-encoded`)
  - https://github.com/rack/rack/blob/master/SPEC#L37-L39
- WSGI specification doesn't say anything about it
  - https://www.python.org/dev/peps/pep-0333/#id19
- CGI specification defines 'Unlike a URI path, the PATH_INFO is not URL-encoded'
  - https://tools.ietf.org/html/rfc3875#section-4.1.5

Considering mruby in h2o, the compatibility to other servers is important for portability and "least surprise". So I think it's best if we can change it undecoded, but it may break backward compatibility if the users already use and depend on decoded one.

Dear users: if you have any thoughts or suggestions on this, please share them with me by adding comments!

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

I would appreciate it if you could add tests for corner cases, e.g.: `paths` is set to `/abc/` and input is `/abc/def/../ghi/../jhk` (I assume the expected output is `/ghi/../jhk`.

**Comment by kazuho** [comment]
Sorry, what I was trying to say is to have a test that assures:
* input path being normalized into a different length does not cause PATH_INFO to become corrupt
* PATH_INFO does not get normalized in such case

e.g., something something like `/123/../abc/def/../ghi` returns an expected output (`/def/..ghi`).

**Comment by i110** [comment]
@kazuho Thank you for the clarification. I added some tests and fix one bug.

**Comment by kazuho** [comment]
Let's have this merged now that we have seen no complaints after one week. Thank you for working on the issue.

**Pull request merged**
