### PR TITLE
allow using bundled ssl in libh2o and libh2o-evloop

### PR DESCRIPTION
**Pull request by iceb0y**
#290 I think it doesn't harm to allow using the bundled ssl in library.

I'm building a Python binding for h2o: https://github.com/iceb0y/pyh2o

If this is supported, I can remove the dependency to openssl.

### CODE REVIEW

**Comment by kazuho** [comment]
@iceb0y Thank you for the PR.

> I think it doesn't harm to allow using the bundled ssl in library.

I think it does.

In case of python, you might want to use pyh2o alongside another library that depends on OpenSSL. Such configuration only works if the two libraries refer to the OpenSSL functions through dynamic linking (i.e. link them using shared libraries).

If you embed OpenSSL (or libressl) within libh2o, then such configuration would no longer work (or the users would start seeing strange errors) since there would be two libraries (i.e. libh2o and libssl) that have functions with same names.

**Comment by iceb0y** [comment]
The way `pyh2o` works is to build a dynamic library with all dependencies statically linked, and it's loaded by python at runtime. At least the generated `.so` file on linux has `libc`, `h2o`, `openssl`, `wslay` symbols. I know this seems weird, but I want to make it installable by a single command `pip install pyh2o` on windows/osx/linux.

There is another project `uvloop` which does the same thing, and I found [it's impossible to share `libuv` between multiple libraries](https://github.com/MagicStack/uvloop/issues/52) before. I think it's a function lack in python's package manager.

Please also see my question in #99 (unrelated) as it seems not being noticed.

**Comment by kazuho** [comment]
@iceb0y 
> The way `pyh2o` works is to build a dynamic library with all dependencies statically linked, and it's loaded by python at runtime. At least the generated `.so` file on linux has `libc`, `python`, `h2o`, `openssl`, `wslay` symbols. I know this seems weird, but I want to make it installable by a single command `pip install pyh2o` on windows/osx/linux.

I wouldn't mind adding the proposed feature as long as it is kept optional, but as I said, I think that it is not a good idea.

Consider the following case.

`pyh2o` bundles libh2o with has libressl bundled. Another python library dynamically loads `libssl` provided by OpenSSL. What would happen here is that the python library trying to call the function of `libssl` would mostly call the functions defined in libressl, since OpenSSL and libressl define functions with same names.

But the two libraries are not binary-compatible, which means that the definition of the structs within the header files of the two libraries are different. Therefore, the python library will to access the members of the structs instantiated by libressl in the way defined in the header files of OpenSSL, which would lead to a crash or some unexpected behavior.

This is, from what I understand, one of the nasty things that could happen with the approach. Do you really want to do this?

**Comment by iceb0y** [comment]
I think it's better to find a way to hide the names in the generated `pyh2o*.so` as they are unnecessary. But using bundled ssl in libh2o is needed. Please review and accept this change. Thanks.

**Comment by kazuho** [comment]
> I think it's better to find a way to hide the names in the generated `pyh2o*.so` as they are unnecessary.

I agree that that is another good way to tackle the issue.

> But using bundled ssl in libh2o is needed. Please review and accept this change. Thanks.

Will do. Please wait for a day or two. Thank you in advance.

**Comment by kazuho** [comment]
Review Comment: How about creating a dedicated parameter (named something like `EMBED_SSLLIB_TO_LIBH2O`) that instructs the build process to embed libcrypto and libssl to libh2o?

Until now, we have _not_ been embedding the contents of the SSL library to libh2o even when `WITH_BUNDLED_SSL` has been set. I would like to continue the design so as not to break compatibility and also because (as stated) I believe that in most cases it is not a good idea to have the library embedded in libh2o.

**Comment by iceb0y** [comment]
Actually ssl library is not embedded into h2o. User program has to link h2o, ssl, crypto.

**Comment by kazuho** [comment]
@iceb0y Sorry for the delay.

> Actually ssl library is not embedded into h2o. User program has to link h2o, ssl, crypto.

Thank you for the clarification. Am I understanding correct that you would like to build libh2o with the accompanying version of libressl, but have them left under the build directory as separate libraries?

That sounds fine to me, but I would still like to request to have a dedicate parameter for instructing CMake to build it in such way (as originally suggested in https://github.com/h2o/h2o/pull/1158#issuecomment-270841118), possibly using a different name (e.g. `WITH_BUNDLED_SSL_FOR_LIBH2O`).

**Comment by iceb0y** [comment]
PR updated to use the dedicate parameter as suggested. Please review.

**Comment by iceb0y** [comment]
ping

**Comment by kazuho** [comment]
We no longer bundle libressl (see #1546).

**Pull request closed without merging**
