### PR TITLE
[h2olog] add a small E2E tests for h2olog to attach an h2o server process

### PR DESCRIPTION
**Pull request by gfx**
Tested on Ubuntu 20.04 on VMware. Unfortunately, I cannot run `h2olog` on Travis CI instances. I'm not sure it's really impossible or not because `bpftrace`, which also depends on iovisor/bcc, works on Travis CI instances, though.

FYI I've installed `bpfcc-dev` with `apt`, but you need to build [iovisor/bcc](https://github.com/iovisor/bcc) if you use older Ubuntu.

(re-created from https://github.com/gfx/h2o/pull/1)

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for working on this PR.

Just curious; would it be possible to rewrite t/90dtrace.t using h2olog? It is my understanding that we'd be sunsetting the use of bpftrace in place of h2olog. Then, I think that rewriting t/90dtrace.t might be the correct thing to do.

**Comment by gfx** [comment]
It is not directly possible because `h2olog` targets only Linux. However, it sounds good to drop `bpftrace` dependency by just removing bpftrace part in ` t/90dtrace.t` and adding a new one using h2olog, if the portability itself doesn't matter.

**Comment by kazuho** [comment]
@gfx We can drop macOS from the tests.

Or to be precise, having tests for linux _and_ not having redundant tests is more important than having a wide-range of tests for macOS.

**Comment by gfx** [comment]
To use h2olog in tests like `t/90dtrace.t`, we need to extend h2olog to trace more events, as issued in https://github.com/toru/h2olog/issues/84

**Comment by gfx** [comment]
Closing in favor of https://github.com/h2o/h2o/pull/2520

**Pull request closed without merging**
