### PR TITLE
tests are failing because of address re-use

### PR DESCRIPTION
**Pull request by deweerdt**
A common case for test failures is due how tests are using
`empty_port()` to obtain addresses to bind to. This is inherently racy,
because of a TOCTOU race: we first check if the port is not used, then
bind it.

This implements a workaround by providing two functions:
`safe_empty_port()` and `safe_empty_port_release()`. When the
SAFE_EMPTY_PORT_DIR environment variable is set, these functions use a
file as a lock in that directory, so that another sibling process
doesn't obtain the same port. When the port is allocated, we create an
empty file with the port name in that directory, and other tests will
keep retrying to obtain a port if the file exists.

### CODE REVIEW

**Comment by kazuho** [comment]
Is your intention trying to fix failures when running many tests concurrently (by using `prove -j` for example)?

If that is the case, I'd suggest switching to a different approach of locating empty ports.

At the moment, Net::EmptyPort tries to allocate an empty port initially from 1500 canditates (see https://github.com/tokuhirom/Test-TCP/blob/master/lib/Net/EmptyPort.pm#L48), which might be considered smaller than ideal, especially when you are running multiple tests at once.

We could possible change the code to use bind (2) with the port number set to zero. Called that way, the system call assigns the socket an unused ephemeral port.

This approach will likely work well, since most operating systems assign ephemeral ports using a single counter that is incremented every time a port is assigned.

**Comment by deweerdt** [comment]
> We could possible change the code to use bind (2) with the port number set to zero. Called that way, the system call assigns the socket an unused ephemeral port.

I think that would be best, agreed. That means that we need a way to obtain the port that H2O is running on after startup, for example printing it to stderr, would that approach work for you?

**Comment by kazuho** [comment]
@deweerdt 
> That means that we need a way to obtain the port that H2O is running on after startup, for example printing it to stderr, would that approach work for you?

What I am suggesting is to let `empty_port` call `bind` with port set to zero and use the returned port when we launch H2O, hoping that the ephemeral port returned by the OS will not get reused for certain amount of time.

The approach does not totally eliminate the possibility of collision, but it might work substantially better than the current approach.

How does it sound?

**Comment by deweerdt** [comment]
> What I am suggesting is to let empty_port call bind with port set to zero and use the returned port when we launch H2O, hoping that the ephemeral port returned by the OS will not get reused for certain amount of time.

Ah I see, I thought you meant modifying H2O to work with dynamically allocated ports (it's possible to currently pass `0` as the port in the config, but different threads will end up with different ports, and the listener setup code will complain that two listeners share the same port).

I think that what you suggest (having `empty_port()` call `bind(3)`), will work better than the current implementation. However, passing `0` and then reading back the port from the logs might solve the issue in a more definite way. Plackup and Starlet would need minor changes to accept `0` as the listening port. If we do go that route, I might as well start there. Let me know which solution you prefer.

**Comment by kazuho** [comment]
Thank you for your thoughts.

> I think that what you suggest (having `empty_port()` call `bind(3)`), will work better than the current implementation. However, passing `0` and then reading back the port from the logs might solve the issue in a more definite way. Plackup and Starlet would need minor changes to accept `0` as the listening port. If we do go that route, I might as well start there. Let me know which solution you prefer.

Yes, having `empty_port()` call `bind(3)` is what I have in mind.

While I agree that implementing in each server the ability to listen to an available port is a solution that would work perfectly, I am worried about the cost and the lack of reusability of the approach. The issue is that we would need to add the feature to every server we would use in our tests.

Considering that, my two cents go to at first modifying `empty_port()` and to see if it works well.

**Comment by deweerdt** [comment]
@i110 submitted a better fix for Test-TCP: https://github.com/tokuhirom/Test-TCP/pull/59
Closing

**Pull request closed without merging**
