### PR TITLE
Warn if `time` is not in $PATH

### PR DESCRIPTION
**Pull request by adrianheine**

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

It is surprising to me that there could be platforms without `time (1)`. May I ask the platform that you are asking, that lacks the command?

I am wary of adding code (or script) to handle exotic platforms. I'm inclined to argue that we should just stop using `time` if we need to care about platforms without the command.

**Comment by adrianheine** [comment]
Thanks for your comment! Actually, none of my Debian systems (servers and desktops) have `time (1)`, I always use the bash [reserved word](https://man7.org/linux/man-pages/man1/bash.1.html#RESERVED_WORDS).

**Comment by kazuho** [comment]
@adrianheine Oh, I did not know that was the case. Thank you. I agree that this is a real issue.

Learning that, I've given some thought, however am hesitant to adding code for detecting missing dependencies of the tests. `run_tests` script being wrapped by `time` invokes perl and loads a lot of perl modules. Unless all those exist, the test fails. I think that's also a real concern.

But I do not want to start adding warnings for every missing perl modules or executables that are needed. People can look at the error messages and figure them out themselves.

**Comment by adrianheine** [comment]
That's true, I ran into several missing perl modules myself and it was pretty straight-forward to determine and install the corresponding packages.

The error message you get for not having `time` installed on `make check` is a bit less obvious but still understandable:
> env: 'time': No such file or directory

On the other hand, with my patch, if you ignore or overlook the warning, `make check` produces:
> env: 'TIME-NOTFOUND': No such file or directory

Which is definitely worse.

**Pull request closed without merging**
