### PR TITLE
Verify client certificates

### PR DESCRIPTION
**Pull request by kazuho**
This PR adds support for client authentication using certificates.

`client-CA-file` parameter sets the trust anchor of the client certificates. If used, access would be allowed from only the clients that can be verified as trusted by the specified trust anchor.

There is (still) no support for using client certificates for authentication while delegating authorization to web applications.

Subsumes #2621. Incorporates https://github.com/h2o/picotls/pull/360.

### CODE REVIEW

**Comment by kazuho** [comment]
@ha0li Would you mind checking if I haven't broken anything. Thank you for all the work.

**Comment by ha0li** [comment]
@kazuho Thank you for this and the other PR in picotls. I'll verify and provide update.

**Comment by ha0li** [comment]
@kazuho I checked the changes and tested locally myself, it is good to go! Thank you, and I think that your approach that use verify flags at the x509_store level is smart, and it keeps picotls clean.

**Comment by kazuho** [comment]
@ha0li Thank you for checking. Merged.

**Pull request merged**
