### PR TITLE
Add .spec file for building RPMs

### PR DESCRIPTION
**Pull request by funzoneq**
Here is a the source .spec file that is required for building RPMs.

The resulting RPM file can be found here: http://vps.us.freshway.biz/CentOS-6-Production-x86_64/RPMS.freshway/h2o-1.2.0-2.el6.x86_64.rpm

And the .src.rpm that can be used to rebuild for centos/redhat/suse: http://vps.us.freshway.biz/CentOS-6-Production-x86_64/RPMS.freshway/h2o-1.2.0-2.el6.src.rpm

### CODE REVIEW

**Comment by kazuho** [comment]
@funzoneq Thank you for the file.

It definitely looks useful, however I do not want to maintain configuration files for every packaging manager within the repository (since they are expected to work after the source repository gets shipped as a stable version).

Does it make sense for you to create a separate repository (like `github.com/h2o/h2o.rpm`) and have the spec file stored there?

**Comment by funzoneq** [comment]
@kazuho Yeah that makes sense. That way we can also setup continuous integration and publish the RPMs somewhere.

**Comment by kazuho** [comment]
@funzoneq Thank you!  Created github.com/h2o/h2o.rpm with write privileges granted to you.  If you have any issues please let me know.

**Comment by funzoneq** [comment]
@kazuho I see the repository, but don't seem to have write privileges yet.

```
[arnoud@imgbuilder h2o.rpm]$ git push
ERROR: Permission to h2o/h2o.rpm.git denied to funzoneq.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by funzoneq** [comment]
Resolved. The e-mail just came in.

**Comment by kazuho** [comment]
Thank you for your works on h2o.rpm!!

**Comment by funzoneq** [comment]
Thank you for h2o :) Happy to contribute.

**Pull request closed without merging**
