### PR TITLE
[http2] rapid reset attack

### PR DESCRIPTION
**Pull request by kazuho**
TBD

### CODE REVIEW

**Comment by dch** [comment]
will this be backported to the old 2.2.6 release, or should we consider that deprecated?

**Comment by kazuho** [comment]
Thank you for checking. Please consider all the tagged releases as deprecated.

**Comment by kishorenc** [comment]
Are there plans to do further releases? This question has been asked a few times but I haven't seen a concrete answer. It would be great if you can clarify @kazuho.

**Comment by hfujita** [comment]
I think this helps:
https://h2o.examp1e.net/install.html
> Release Policy
> As of April 2023, we have ceased to release versions. Rather, the each commit to master branch is considered stable and ready for general use except for the features marked as experimental.

**Pull request merged**
