### PR TITLE
qpack: do not derefence a pointer before range check

### PR DESCRIPTION
**Pull request by hfujita**
This fixes a ClusterFuzz issue 35675.

### CODE REVIEW

**Review by kazuho — COMMENTED** [review]
Thank you for the fix!

Can we do something like below for consistency? I understand that the proposed fix works though it goes away from our coding pattern by reading in the reverse order.
```c
if (!(*src < src_end))
    goto Fail;
int is_huff = (**src & 0x80) != 0;
```

**Comment by hfujita** [comment]
I'm not sure if I understand your intention here. So your concern is the introduction of `src_head`? I did so because I thought `*src` could be advanced in `decode_int`. If that is the case, referencing to `*src` would change the behavior of the code.

My assumption is simply based on the function prototype of `decode_int`, so I might be missing some more context (maybe there's a guarantee that `*src` would not be advanced?).

**Comment by kazuho** [comment]
I think we are on the same page regarding how the code works.

What I am concerned is that the proposed code reads the bits in the reverse order, and doing so might cause confusion.

I think we can fix the bug by adding a check _before_ reading the the huffman bit? Doing that might not be optimal in terms of CPU cycles but I think we'd prefer readability here.

```c
if (!(*src < src_end))
    goto Fail;
int is_huff = (**src & 0x80) != 0;

if (decode_int(&len, src, src_end, 7) != 0 || len > MAX_HEADER_VALUE_LENGTH) {
    ...
```

**Comment by hfujita** [comment]
@kazuho Oh sorry I did miss the details of your comment. Now I understand your intention. Does 655039b look good?

**Comment by kazuho** [comment]
Thank you! It does.

**Pull request merged**
