### PR TITLE
Added support for HEAD-requests to the file handler

### PR DESCRIPTION
**Pull request by mback2k**
First try to implement issue #78.

### CODE REVIEW

**Comment by bagder** [comment]
It would probably make sense to also make sure to send back a "proper" response code for non-recognized methods while you're at it changing this code path. Just sending back a 404 when we send "MOO" as a request is weird and not HTTP/1.1 compliant.

**Comment by mback2k** [comment]
@bagder Implemented by returning 405 Method Not Allowed and Allow header for methods other than GET or HEAD.

**Comment by kazuho** [comment]
@mback2k @bagder 
Thank you for the PR and the advises.  I am fine to merge the PR once the issues get fixed.

**Comment by mback2k** [comment]
@kazuho Thanks for spotting the mistakes and your suggestions. I implemented them and also added some simple unittests based upon the existing ones.

**Comment by kazuho** [comment]
Thank you for the fix and the tests!  Made some tweaks and merged to master.

**Pull request merged**
