### PR TITLE
An API to selectively disable automated IO on reads and writes

### PR DESCRIPTION
**Pull request by deweerdt**
- We rename `H2O_SOCKET_FLAG_DONT_READ` to the more general
  `H2O_SOCKET_FLAG_DONT_IO`, since that flag can be used to be notified
  of writes as well.
  When that flag is set, `h2o_socket_write()` and
  `h2o_socket_read_start()` can be used to be notified that the
  underlying socket is ready for write or read respectively.
- Add a `h2o_socket_dont_io()` function to tweak said flag

### CODE REVIEW

**Comment by kazuho** [comment]
As discussed off-line, providing `h2o_socket_dont_read` function to modify the flags seem OK to me.  With that change only, the reading side would work fine.

For the writing side, I think we should create a new function that registers an _one-shot_ IO-less write callback.

The reason why the function should be _one-shot_ (i.e. applications need to register the callback every time it faces a partial write) is since then we can reuse the H2O_SOCKET_FLAG_IS_CONNECTING flag for the purpose (maybe we should rename it to H2O_SOCKET_FLAG_DONT_WRITE).

To avoid me from causing accidental regressions on your branch, I'd like to keep the changes made by this feature request as small as possible, and in that respect, reusing an existing flag (instead of introducing a new one) would be a good thing.

**Comment by deweerdt** [comment]
That sounds good, thanks for your feedback. Here's another take, with IS_CONNECTING renamed to DONT_WRITE, and the necessary hook in `do_write` to skip the writing.

**Comment by deweerdt** [comment]
Modified the write API to put everything under a `h2o_socket_notify_write` function, this simplifies the callers and makes the code change smaller.

**Comment by kazuho** [comment]
Thank you for the changes!  Looks great.

**Pull request merged**
