### PR TITLE
h2olog: make sure `generated_raw_tracer.cc` is fresh by generating it for each time

### PR DESCRIPTION
**Pull request by gfx**
This is extracted from https://github.com/h2o/h2o/pull/2520

### CODE REVIEW

**Review by kazuho — COMMENTED** [review]
Can you please describe the problem that this PR is trying to solve?

I ask this because status quo seems to be using `DEPENDS` correctly. Or is it the case that the generated file is missing the [GENERATED](https://cmake.org/cmake/help/latest/prop_sf/GENERATED.html) property?

**Comment by gfx** [comment]
I saw CI failure because `generated_raw_tracer.cc` was not fresh, which might confuse the CMake dependency checker.  I'm not 100% sure about it, but CMake might not able to handle dependencies correctly for those repos which have been cloned and not edited. It makes sense if CMake uses `mtime` for dependency check, because `git clone` does not set `mtime` but instead files' `mtime` are the time at the git-clone. 
 

---

re: `GENERATED`: 

As the [add_custom_command](https://cmake.org/cmake/help/latest/command/add_custom_command.html) doc says:

> OUTPUT
> (snip)
> Each output file will be marked with the GENERATED source file property automatically. 

So I think the generated file is already marked as GENERATED.

**Comment by kazuho** [comment]
@gfx Thank you for the response.

> I saw CI failure because generated_raw_tracer.cc was not fresh, which might confuse the CMake dependency checker. I'm not 100% sure about it, but CMake might not able to handle dependencies correctly for those repos which have been cloned and not edited. It makes sense if CMake uses mtime for dependency check, because git clone does not set mtime but instead files' mtime are the time at the git-clone.

I'm not sure if I fully follow your argument. It sounds like the argument is built around the assumption that change detection based on mtime is going to fail. But if that is the case, wouldn't change detection of any source file become an issue? Maybe I'm missing something, but I do not see how it can specifically be related to automatically generated source files.

> So I think the generated file is already marked as GENERATED.

Thank you for pointing that out. Good to know.

**Comment by gfx** [comment]
> I'm not sure if I fully follow your argument. It sounds like the argument is built around the assumption that change detection based on mtime is going to fail. But if that is the case, wouldn't change detection of any source file become an issue? Maybe I'm missing something, but I do not see how it can specifically be related to automatically generated source files.

I think the mtime-based change detection fails if a generated file is committed to the repo and thus it exists immediately after git-clone. If the generated file does not exist, CMake will execute a task to generate the file without checking its dependencies. On the other hand, if the generated file exists (it's our case),  CMake may not handle the dependency check correctly because dependency's mtimes are not reliable, pointing to the time when git-clone happened. This is my inference based on the assumption that CMake uses mtime to detect changes in dependencies. What do you think of it?

**Comment by kazuho** [comment]
@gfx Thanks. I have two points.

If there's chance of us seeing commits that update dependenies while leaving the automatically generated file as-is, I think we should revisit our decision to include the automatically generated file in the repository. Current approach is based on the premise that it helps us review the code by having the automatically generated file in the repository. It sounds like that approach is not working in a reliable manner.

Taking a look at the CMake docs, https://cmake.org/cmake/help/latest/command/add_custom_command.html states:
> If DEPENDS is not specified, the command will run whenever the OUTPUT is missing; if the command does not actually create the OUTPUT, the rule will always run.

So removing DEPENDS makes things worse, because when there is a mismatch, the automatically file would never be generated. Am I correct?

**Comment by gfx** [comment]
> So removing DEPENDS makes things worse, because when there is a mismatch, the automatically file would never be generated. Am I correct?

Yikes! Agreed that this PR does make things worse. And also agreed that this approach is not working in a reliable manner since we probably violate the preconditions on CMake's dependency detection.

However, I'd like to keep the generated file to be committed not only for code review but also for the development of h2olog.  Its benefits are immeasurable when we develop a code generator that emits thousands of lines of code: any tiny changes in a generated file can be detected with no effort, and the result of updating `*-probes.d` is very clear. 

So I'd like to find a workaround that makes things work. How about deleting the generated file in running `cmake` 
 to configure, keeping `DEPENDS` as is? It's meant to fix the violation of the preconditions at configure time.

**Comment by kazuho** [comment]
> However, I'd like to keep the generated file to be committed not only for code review but also for the development of h2olog. Its benefits are immeasurable when we develop a code generator that emits thousands of lines of code: any tiny changes in a generated file can be detected with no effort, and the result of updating `*-probes.d` is very clear.

What I am saying is that this argument becomes questionable when the basis of this PR is to fix the generated file and the dependencies being out-of-sync. Them being out-of-sync means that we are failing to see the correct thing.

**Comment by gfx** [comment]
Talked with @kazuho elsewhere and we have agreed that we do not change the code generation.

1. The h2olog tests will fail if the generated file is stale. That's totally okay because the generated file *is* stale -- it should be re-generated and committed.
2. If a developer removes USDTs from probes.d on macOS, it makes the h2olog tests fail because of (1).  Executing `./src/h2olog/misc/gen_raw_tracer.py . ./src/h2olog/generated_raw_tracer.cc` will regenerate the generated file and resolve this problem. 

So closing this PR and removing this change from #2520.

**Pull request closed without merging**
