### PR TITLE
use atomics in place of mutexes Fixes #98

### LINKED ISSUE #98: Few heavy locks on socketpool.c
Hello !

I found 3 places on socketpool.c where a full mutex lock/unlock are used to only update an integer variable:

pthread_mutex_lock(&pool->_mutex);
--pool->_shared.count;
pthread_mutex_unlock(&pool->_mutex);

Wouldn't be a good fit for "__sync_fetch_and_add(pool->_shared.count, +- 1)" ?

Cheers !

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
I don't know how the unit tests, I simply loaded up the home page in a browser twice, and then ran `wrk -c 100 -t 100 http://localhost:8080` against it.  I'm not sure how valid that is to test, but atleast things looked slightly better:
Before:
```
wrk -c 100 -t 100 http://localhost:8080
Running 10s test @ http://localhost:8080
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.42ms    3.77ms  28.95ms   86.58%
    Req/Sec   396.51    152.00   777.00     53.85%
  374886 requests in 9.99s, 143.01MB read
Requests/sec:  37515.11
Transfer/sec:     14.31MB
```
after:
```
wrk -c 100 -t 100 http://localhost:8080
Running 10s test @ http://localhost:8080
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.23ms    4.05ms  34.73ms   88.09%
    Req/Sec   427.90    160.20   777.00     64.60%
  403781 requests in 9.99s, 154.03MB read
Requests/sec:  40417.98
Transfer/sec:     15.42MB
```

**Comment by kazuho** [comment]
Thank you for the PR.

Please rewrite other parts of that use `_share.count` to use the sychronised operations, or the numbers might become incorrect.

Regarding the benchmark number,s I am afraid they are not due to the change, since the code path is only used by the reverse proxy module.

**Comment by nickdesaulniers** [comment]
How's that look?  Let me know if you'd prefer them squashed, I can do that.

**Comment by kazuho** [comment]
Thank you for the work.  Merged to master.

Generally speaking I would be happy if you do not squash on your behalf as it would help us recall how we changed the code as the discussion went on.

**Pull request merged**
