### PR TITLE
Fuzzer macosx fixes

### PR DESCRIPTION
**Pull request by deweerdt**

### CODE REVIEW

**Comment by kazuho** [comment]
@deweerdt @zlm2012 Thank you for adding fuzzer support for OS X. Is this branch ready for merge?

**Comment by deweerdt** [comment]
This is now ready for merge, @kazuho. Thanks!

**Comment by zlm2012** [comment]
Sorry for being late. I checked again and at least building is okay. I will check running tests if needed.

**Comment by zlm2012** [comment]
Test have been run. Should be okay.

**Comment by kazuho** [comment]
@deweerdt @zlm2012 Thank you for working on this issue. Here we go for merge.

**Pull request merged**
