### PR TITLE
add support for brotli

### PR DESCRIPTION
**Pull request by kazuho**
WIP.

The strategy is:
* change `file.send-gzip` to `file.send-compress`
 * send `.br` whenever possible
* change `gzip: ON` to `compress: ['gzip', 'brotli']`
 * always prefer `brotli` if both are specified?

implements #660

### CODE REVIEW

**Comment by utrenkner** [comment]
Hi @kazuho, I am excited to see work in getting brotli-support into h2o

I completely agree with the first part of the strategy: If a .br file exists and the client can handle brotli, then that file should be served. Else gzip. Else non-compressed.
NB: I will soon start writing a little shell script, which runs through the docroot and tries to compress assets with gzip (or zopfli) and brotli. Only where gzip/zopfli at highest compression level results in a file which is smaller than the original, will it be stored. And only where brotli at highest level results in a file which is smaller than the .gz or non-comprssed file, will it be stored. Thus h2o would always serve the smallest file acceptable to the browser (I recently tried to gzip thousands of small and very small files and found that quite often, the gzipped files were larger than the original... when the original was was less then 30 bytes).

About the second strategy, I am not quite sure. It would depend on the compression level used. From the reading of [this](https://blog.cloudflare.com/results-experimenting-brotli/) and [this](https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html) article, it becomes clear that both, gzip and brotli are very slow when used with high compression levels (i.e. unsuitable for on-the-fly compression). However, in the second article, Tim Kadlec shows that brotli at level 4 still outperforms gzip at its default level of 6 (both in compression time and in resulting file size) - for actual typical assets. So, with these settings, I would agree with your strategy.

Another question remains the "is_compressible" flag (see also  #655 ). We may find out, that certain algorithms perform well on one type of files but not on another. In [this article](https://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/) Jeff Atwood shows that you can nicely compress PNG files with zopfli (the resulting files are gzip compatible). Usually, we would never think of PNG as "compressible" yet zopfli seems to be able to do just that. In its current design with `file.send-gzip`, h2o would never even look for *.png.gz files. If we are very serious about this compression optimisation we may have to map file/mime types to certain algorithms. E.g. "is_gzip_compressible". But maybe this would become too complex in the end?

**Comment by utrenkner** [comment]
I thought a little longer about the is_compressible issue mentioned above.

Currently the way to register additional file extensions as is_compressible is through the configuration - by first removing and than re-adding a mime-type and its file extension (seen in [this issue](https://github.com/h2o/h2o/issues/767#issue-132701266)):
```
file.mime.removetypes: [".js"]
file.mime.addtypes:
  "application/javascript":
    extensions: [".js"]
    is_compressible: yes
    priority: highest
```
This seems overly complicated. What I would like to see is a configuration, similar to your example for how to let [mruby](https://h2o.examp1e.net/configure/mruby.html) set the max-age header for certain file extensions:
```
        if /\.(css|js|svg|png|jpe?g|gif|ico|eot|otf|woff2?|ttf)$/i.match(env["PATH_INFO"])
          headers["cache-control"] = "max-age=86400"
        end
```
I think h2o should come with a reasonable set of mappings for which mime-types are generally compressible (i.e. everything which is basically text). But the configuration should allow to easily add other files, depending on their extension:
```
is_compressible.add-filetype: js,json
is_gzip_compressible.add-filetype: png
is_brotli_compressible.add-filetype: ...
```
Does this make sense?

**Comment by kazuho** [comment]
@utrenkner Thank you for your comment.

> About the second strategy, I am not quite sure. It would depend on the compression level used. From the reading of [this](https://blog.cloudflare.com/results-experimenting-brotli/) and [this](https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html) article, it becomes clear that both, gzip and brotli are very slow when used with high compression levels (i.e. unsuitable for on-the-fly compression). However, in the second article, Tim Kadlec shows that brotli at level 4 still outperforms gzip at its default level of 6 (both in compression time and in resulting file size) - for actual typical assets. So, with these settings, I would agree with your strategy.

FWIW, the on-the-fly gzip encoder of H2O uses quality level 1 (Z_BEST_SPEED).  We might want to make that configurable.

That said, I think we both understand that the brotli encoder will produce smaller output than the gzip encoder when configured for comparable speed.  Therefore, it is reasonable to prefer using the former whenever possible.  However, I would still like to keep whether or not to use brotli configurable, since IIRC the brotli encoder consumes much more memory than the gzip encoder.

> Another question remains the "is_compressible" flag (see also  #655 ). We may find out, that certain algorithms perform well on one type of files but not on another. In [this article](https://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/) Jeff Atwood shows that you can nicely compress PNG files with zopfli (the resulting files are gzip compatible). Usually, we would never think of PNG as "compressible" yet zopfli seems to be able to do just that. In its current design with `file.send-gzip`, h2o would never even look for *.png.gz files. If we are very serious about this compression optimisation we may have to map file/mime types to certain algorithms. E.g. "is_gzip_compressible". But maybe this would become too complex in the end?

You cannot expect the output of gzip to be compressible by another encoder.  My understanding is that the blogpost discusses using zopfli encoder _in place of_ the original gzip encoder (note: the output of zopfli encoder can be decoded by an ordinary gzip decoder).  In other words, IMO it is fine to keep the `is-compressible` flag as is.

**Comment by kazuho** [comment]
@utrenkner 
> I think h2o should come with a reasonable set of mappings for which mime-types are generally compressible (i.e. everything which is basically text).

Agreed.  The guess is made [here](https://github.com/h2o/h2o/blob/v1.7.0/lib/handler/mimemap.c#L392-L393), but I assume it is not working as it should for certain types such as application/javascript or application/json.

> But the configuration should allow to easily add other files, depending on their extension:

Generally speaking, MIME-types should be the only source of _file-type_, with the exception being the file handler that identifies the MIME-type from the extension of the file being served.  Anyways, whether if we should provide more complex directives depends on whether or not we need to introduce `is_gzip_compressible` et. al; please bring back the point after we resolve the need.

**Comment by utrenkner** [comment]
@kazuho 

Thank you very much for your thoughtful responses.

> You cannot expect the output of gzip to be compressible by another encoder. My understanding is that the blogpost discusses using zopfli encoder in place of the original gzip encoder (note: the output of zopfli encoder can be decoded by an ordinary gzip decoder). In other words, IMO it is fine to keep the is-compressible flag as is.

This is not what I had in mind. Sorry, my C know-how is very limited and therefore, I did not consult the source code. This is what I assumed: The is_compressible defines which files (mime-types) are compressed on-the-fly when `gzip: ON` is configured. AND - so my assumption - it also defines for which files h2o is looking for .gz files when `file.send-gzip: ON` is configured.

Thus, if I wanted to pre-compress my assets, I would have to write the mentioned shell script, which runs through the docroot, identifies files which are compressible and then tries to produce .br and .gz versions which are smaller than the original (and .br smaller than the .gz version). Now, if I used zopfli for the gzip-compression, I could include .png files as it seems that they would benefit from being compressed with zopfli, resulting in a *.png.gz file, which is smaller than the original .gz file.

But if my assumption is correct, then the fact that "image/png" is not set as "is_compressible" would lead to h2o not even checking if a *.png.gz file existed (in the `file.send-gzip: ON` case). For a normal gzip compression (including the on-the-fly gzip compression) this is a reasonable assumption. But for files pre-compressed with zopfli it seems like it is not. Thus, if I used pre-compression with zopfli I would like to have .png files as "is_compressible".

However, one of the key techniques of the brotli algorithm is its static dictionary, which is used in the compression. I have not run any tests, but this makes me strongly believe that it would not work well on PNG files, as they typically do not contain words from such a dictionary.

Thus we would have a situation in which `file.send-compress` should look for the zopfli generated *.png.gz files but not necessarily for *.png.br files. And the on-the-fly `gzip: ON` should also ignore .png files...

This is where my idea comes in: Have a set of well compressible mime-types as a default for "is_compressible" but allow for easy configuration of different files in the configuration. For my pre-zopflied PNGs I could thus add
`is_gzip_compressible.add-filetype: png` or using mime-types
`is_gzip_compressible.addtypes: image/png`

h2o cannot guess that I use zopfli for pre-compression. Thus I should be able to configure it.

> Agreed. The guess is made here, but I assume it is not working as it should for certain types such as application/javascript or application/json.

I know. And I patch that file before each new build of h2o, to add JavaScript and JSON. I add:
`strcmp(mime, "application/javascript") == 0 || strcmp(mime, "application/json") == 0 ||`


Please note, I absolutely do not mind, if you say that my proposal is way to complex for the little additional benefit it may bring. I am not a C-programmer and I only try to explain how I as a user would like to see things work. In the end it should make neither the h2o code nor configuration too complicated.

**Comment by kazuho** [comment]
@utrenkner 
> This is what I assumed: The is_compressible defines which files (mime-types) are compressed on-the-fly when `gzip: ON` is configured. AND - so my assumption - it also defines for which files h2o is looking for .gz files when `file.send-gzip: ON` is configured.

To be correct,
* `is_compressible` flag defines which responses should be compressed by the on-the-fly gzip handler
* if `file.send-gzip` is set to `ON`, then `.gz` file is searched regardless of the MIME-type

> Thus, if I wanted to pre-compress my assets, I would have to write the mentioned shell script, which runs through the docroot, identifies files which are compressible and then tries to produce .br and .gz versions which are smaller than the original (and .br smaller than the .gz version).

I agree.

> Now, if I used zopfli for the gzip-compression, I could include .png files as it seems that they would benefit from being compressed with zopfli, resulting in a *.png.gz file, which is smaller than the original .gz file.

It is true that you can benefit from compressing PNG files using Zopfli.  But creating a `png.gz` file is not the correct way.  Note that PNG is essentially a gzip-ed file (to be correct, most of its portion is encoded using deflate - a header-less variant of gzip).  Therefore, what you should do is use a PNG encoder that uses Zopfli (for example zopflipng provided as part of https://github.com/google/zopfli).

> Thus, if I used pre-compression with zopfli I would like to have .png files as "is_compressible".

As said, PNG file is essentially gzipped already; you cannot expect it to get smaller by applying zopfli or brotli  (I am sorry I wasn't clear in pointing this out in my previous comment).

>> Agreed. The guess is made here, but I assume it is not working as it should for certain types such as application/javascript or application/json.
> 
> I know. And I patch that file before each new build of h2o, to add JavaScript and JSON. I add:
`strcmp(mime, "application/javascript") == 0 || strcmp(mime, "application/json") == 0 ||`
> 
> Please note, I absolutely do not mind, if you say that my proposal is way to complex for the little additional benefit it may bring. I am not a C-programmer and I only try to explain how I as a user would like to see things work. In the end it should make neither the h2o code nor configuration too complicated.

Yeah!  The fact that you knew that javascript and json files were not marked as compressible by default is a good sign that you (as a user) know better than me (the developer of the sever) in certain aspects.  And that is the reason I highly respect your input.

**Comment by utrenkner** [comment]
@kazuho 

> if file.send-gzip is set to ON, then .gz file is searched regardless of the MIME-type

Thank you for the clarification. But if you keep it also for brotli, doesn't it start to add quite some overhead - checking if .br exists, if not, checking if .gz exists... for each single file requested?

And what happens if both `file.send-gzip: ON` and `gzip: ON` are configured: Are they tried sequentially (i.e. "does a pre-compressed file exist? No? Is it a compressible file? YES? Then use gzip on-the-fly"?).

> It is true that you can benefit from compressing PNG files using Zopfli. But creating a png.gz file is not the correct way. Note that PNG is essentially a gzip-ed file (to be correct, most of its portion is encoded using deflate - a header-less variant of gzip). Therefore, what you should do is use a PNG encoder that uses Zopfli (for example zopflipng provided as part of https://github.com/google/zopfli).

This was completely unknown to me. Then, of course, zopfli-compressing existing PNGs does not make sense at all.

> Yeah! The fact that you knew that javascript and json files were not marked as compressible by default is a good sign that you (as a user) know better than me (the developer of the sever) in certain aspects. And that is the reason I highly respect your input.

Thank you! But it was easy for me to spot: I was testing our development site running h2o on www.webpagetest.org. And when `gzip: ON` is configured but you get a bad mark for missing compression on JavaScript files you know something is wrong.

After all this discussion, I can fully support both of your original proposals now! And it would indeed be good to allow configuration of the compression levels for gzip and for brotli. Setting brotli-level: 0 could then completely disable on-the-fly brotli compression as you suggested.

**Comment by kazuho** [comment]
ToDo:
* [ ] add unit and end-to-end tests for on-the-fly brotli
* [ ] accept parameters in the `compress` configuration directive

**Comment by kazuho** [comment]
Separate commands have been introduced for modifying the behavior on-the-fly compressing using the protocol, instead of unifying them under `compress`.

**Comment by kazuho** [comment]
@utrenkner 
> And what happens if both `file.send-gzip: ON` and `gzip: ON` are configured: Are they tried sequentially (i.e. "does a pre-compressed file exist? No? Is it a compressible file? YES? Then use gzip on-the-fly"?).

Correct.

**Comment by mingodad** [comment]
Hello !
You could use the memory pool also to allocate memory for compression see https://github.com/mingodad/h2o/commit/4eb8c91eeca6d072b5f77b34dbc2f9fba09a5c49 .
Cheers !

**Comment by kazuho** [comment]
@mingodad Thank you for the suggestion.

> You could use the memory pool also to allocate memory for compression see mingodad@4eb8c91.

The answer is that you should not.

Memory pool is an optimization with side effects.  The positive side of allocating a _tiny_ chunk of memory from the memory pool is that it is faster than using `malloc`.  The negative side is that the allocated memory is not freed until the pool gets destroyed.

So you should only use pool-based allocation when _all_ of the following conditions are met:
* i) the size of the allocated chunk is tiny
* ii) the total size of the allocated chunks has a small upper bound

The chunks that are used to contain the compressed file content do not fall into the criteria ((i) is not met for gzip.c, both (i) and (ii) are not met for brotli.cc); therefore they should not be allocated from the pool.  It should also be noted that you would see only marginal (if any) boost in performance in this case for using the pool, considering the fact that most of the CPU cycles would nevertheless be spent on on-the-fly compression.

**Comment by utrenkner** [comment]
Yesterday, I wanted to  try the new code but could not get any compression to work. Is it usable in the latest sources? I tried various configurations such as `compress: ['gzip','br']` or just `compress: ['gzip']`. But even `gzip: ON` did not give me any on-the-fly compression anymore.

**Comment by kazuho** [comment]
@utrenkner Can you provide the steps to reproduce the issue?

I see brotli working when using [this configuration](https://gist.github.com/kazuho/cb3181c05ba3dd7b29a7).

2ffbb9689dd57318e92db2d879cddb83

**Comment by utrenkner** [comment]
@kazuho Thank you - without quotation marks it works like a charm: `compress: [ gzip, br ]`

Is it the same syntax for `file.send-compress`, i.e. do I have to specify that "br" is to be looked for? Or is it only ON|OFF?

**Pull request merged**
