### PR TITLE
set SO_RCVBUF & SO_SNDBUF for sockets being reopened

### PR DESCRIPTION
**Pull request by kazuho**
For each worker thread, h2o either duplicates the file descriptor using dup (2), or opens a new file descriptor with the SO_REUSEPORT.

The mode being used depends on certain factors:
* for TCP sockets, the default behavior is the former. The latter is used when SO_REUSEPORT is defined and `tcp-reuseport` option is being set.
* for UDP sockets serving QUIC, the latter is being used whenever SO_REUSEPORT is available, because we want the kernel to distribute ingress UDP traffic by the 4-tuple to the worker threads.

When dup (2) is being used, there is no need to set the socket options for the file descriptor being duplicated, because the options apply to the open file description that is being shared by the original file descriptor and the duplicated descriptor. But when opening new file descriptors with SO_REUSEPORT option, it is necessary to set the options.

But unfortunately, when opening new file descriptors, SO_SNDBUF and SO_RCVBUF options were not set, even though IPV6_PKTINFO was being set. The lack of the code to set  SO_SNDBUF / SO_RCVBUF resulted in only one worker thread having a socket with the expected buffer size, while others were associated with sockets using the default buffer size.

This PR addresses the issue by introducing a function called `set_quic_sockopts` that adjusts all the socket-level options that have to be adjusted. Assuming that we add support for additional parameters to this function, we can avoid falling into the same pitfall in the future.

### CODE REVIEW

**Comment by kazuho** [comment]
@deweerdt @sleepybishop PTAL.

**Review by janaiyengar — APPROVED** [review]
Looks great, thanks @kazuho!

**Review by deweerdt — APPROVED** [review]
Thank you!

**Comment by sleepybishop** [comment]
Great find!

**Pull request merged**
