### PR TITLE
Add MRUBY_CONFIG cmake option

### PR DESCRIPTION
**Pull request by tagomoris**
As cmake option to specify customized `mruby_config.rb` file to add mrbgems.

This change is to build h2o with additional mrbgem dependencies, using an existing `mruby_config.rb` file in application code repository.

```
# in app repo
# git clone h2o
cd h2o
cmake -DWITH_MRUBY=ON -DMRUBY_CONFIG=$(pwd)/../mruby_config.rb .
# and more
```

Editing `h2o/misc/mruby_config.rb` makes situations more complex. If we can specify dependencies in the way like this, it makes writing mruby applications on h2o much easier.

### CODE REVIEW

**Comment by tagomoris** [comment]
Ping?

**Comment by kazuho** [comment]
Could you just extract additional mrbgems to `deps`? misc/mruby_config.rb does `Dir.glob("../mruby-*/mrbgem.rake") do |x| ...`.

Or if that's impossible, I think we should better provide a way to specify additional paths to mrbgems rather than completely replacing mruby_config.rb. We may change misc/mruby_config.rb as time goes; I am afraid people using custom mruby_config.rb might have hard time tracking the changes.

**Comment by tagomoris** [comment]
We're using `iij/mruby-require` in our application, and it requires to be added at the last of all mrbgems. `Dir.glob` doesn't work in such situation.

I agree that it's better to have "additional mrbgems list" in `mruby_config.rb`. 
Now I have two ideas about specifying additional mrbgems in default `mruby_config.rb`.

First:

```ruby
# my_mruby_config.rb
conf.gem :github => '...'
conf.gem :mgem => '...'

conf.gem :github => 'iij/mruby-require'

# h2o/misc/mruby_config.rb
MRuby::Build.new do |conf|
  # existing lines...
  # ...

  if ENV['MRUBY_CONF_EXT_PATH'] && File.exist?(ENV['MRUBY_CONF_EXT_PATH'])
    path = ENV['MRUBY_CONF_EXT_PATH']
    eval(File.read(path), binding, path)
  end
end
```

Of course, `eval` makes many troubles. I have another idea to list mrbgems in Env vars. For example:

```ruby
MRBGEM_LIST = ENV['MRBGEM_LIST'].split(';')

MRuby::Build.new do |conf|
  # existing lines
  # ...
  Dir.glob(...) do |x|
  end

  MRBGEM_LIST.each do |spec|
    if spec.start_with?("mgem:")
      name = spec.sub("mgem:", "")
      conf.gem :mgem => name
    elsif spec.start_with?("git:")
      # ...
    elsif spec.start_with?("github:")
      # ...
    else # path
      conf.gem spec
    end
  end
end
```

This design requires many lines of code and complex syntax (especially for the option of `:branch` in `:git/:github`).

How do you feel about these idea?

**Comment by kazuho** [comment]
Thank you for the proposals. My preference goes to the first (i.e. read the file and evaluate). I'd assume that their could be operations specific to each gem that needs to be done. The only way to support such operations is through `eval`.

**Comment by tagomoris** [comment]
Okay, I'll implement it using `eval` (and will create another pull-request).

**Comment by kazuho** [comment]
:+1: Or it might be possible to use `require` considering the script is run using MRI.

**Comment by tagomoris** [comment]
`require` doesn't bring the binding, so it's needed to be implemented with a bit hacky code.
So I think the current code is good enough to satisfy our (my) requirement.

**Comment by kazuho** [comment]
Closing in favor of #1446.

**Pull request closed without merging**
