### PR TITLE
Move version infomation to CMakeLists.txt.

### PR DESCRIPTION
**Pull request by omasanori**
This makes it possible to generate files depending on the version of h2o from CMake. For example, we can provide h2o.pc pkg-config file without bumping version information in both version.h and h2o.pc.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  I agree that providing a pkg-config file is a good idea, and I understand that in order to generate the file using CMake it is mandatory for CMake to know the version of the library it is building.

Could you please change the PR to _read_ the version number from the header file, instead of generating the header file?

This is because I would like to keep the source files usable without running CMake.  For example, I want to continue to allow users to include the necessary headers (and source files) of the repository, and use them as part of their projects (wo. running CMake).  Generating a header file with CMake and letting the library read the file conflicts with the objective.

**Comment by omasanori** [comment]
Sure. I will do so. Closing for now.

**Comment by kazuho** [comment]
@omasanori In case it is hard to use the version number written in the header file, it is acceptable to generate the header file __and__ include the generated file in the repository.  The approach is does seem a bit ugly, but would work fine under the assumption that re-creating the header file would not cause any issues in case of Git.

**Comment by omasanori** [comment]
Thank you for your consideration. So,

1. Put version information into CMakeLists.txt,
1. Add a custom target, say 'make versiion' to update the header, and
1. Write a note for maintainer to make sure to execute the target after bumping the version.

Are you happy with this?

**Comment by kazuho** [comment]
@omasanori Can we omit step 2 if we simply use the `CONFIGURE_FILE` as has been done in the PR?

Yes it might overwrite the file every time cmake is being run, but IMO it would not cause any negative effect since the contents of the file would remain unchanged.

**Comment by omasanori** [comment]
@kazuho We can, but instead of `make version`, we have to remove caches and run CMake every time we bumped the version.

(`cmake` should not modify the source files implicitly IHMO, and that is why I made version.h in ${CMAKE_BINARY_DIR}. However, I will follow your direction.)

**Comment by omasanori** [comment]
Well, removing caches is not required even if we generate version.h in the source directory. Any `make` target will call `cmake` implicitly whenever CMakeLists.txt is modified.

**Comment by kazuho** [comment]
Thank you for checking if the approach is feasible.

> (`cmake` should not modify the source files implicitly IHMO, and that is why I made version.h in ${CMAKE_BINARY_DIR}. However, I will follow your direction.)

I agree that the approach is ugly, but I think enforcing CMake to always keep the version number in the header file in sync would minimize the risk of releasing a build with wrong version number while not causing issues.

**Comment by omasanori** [comment]
OK, it makes sense. I'll work on it.
Thanks for your constructive suggestions.

**Pull request closed without merging**
