### PR TITLE
error code on RST_STREAM for cancelled push promises is negative

### PR DESCRIPTION
**Pull request by deweerdt**

### CODE REVIEW

**Comment by deweerdt** [comment]
We could maybe catch those at compile time with something like:
```
diff --git a/include/h2o/http2_internal.h b/include/h2o/http2_internal.h
index 416ba2a..9d1b8b4 100644
--- a/include/h2o/http2_internal.h
+++ b/include/h2o/http2_internal.h
@@ -237,7 +237,12 @@ int h2o_http2_update_peer_settings(h2o_http2_settings_t *settings, const uint8_t

 /* frames */
 uint8_t *h2o_http2_encode_frame_header(uint8_t *dst, size_t length, uint8_t type, uint8_t flags, int32_t stream_id);
-void h2o_http2_encode_rst_stream_frame(h2o_buffer_t **buf, uint32_t stream_id, int errnum);
+void h2o_http2_encode_rst_stream_frame_(h2o_buffer_t **buf, uint32_t stream_id, int errnum);
+#define BUILD_BUG_ON(condition) ((void)sizeof(char[1 - 2*!!(condition)]))
+#define h2o_http2_encode_rst_stream_frame(buf, stream_id, errnum) \
+    BUILD_BUG_ON(__builtin_constant_p(errnum)?(errnum < 0):0); \
+    h2o_http2_encode_rst_stream_frame_(buf, stream_id, errnum);
+
 void h2o_http2_encode_ping_frame(h2o_buffer_t **buf, int is_ack, const uint8_t *data);
 void h2o_http2_encode_goaway_frame(h2o_buffer_t **buf, uint32_t last_stream_id, int errnum, h2o_iovec_t additional_data);
 void h2o_http2_encode_window_update_frame(h2o_buffer_t **buf, uint32_t stream_id, int32_t window_size_increment);
diff --git a/lib/http2/frame.c b/lib/http2/frame.c
index 9d03656..fc6ed4c 100644
--- a/lib/http2/frame.c
+++ b/lib/http2/frame.c
@@ -81,7 +81,7 @@ static uint8_t *allocate_frame(h2o_buffer_t **buf, size_t length, uint8_t type,
     return h2o_http2_encode_frame_header((uint8_t *)alloced.base, length, type, flags, stream_id);
 }

-void h2o_http2_encode_rst_stream_frame(h2o_buffer_t **buf, uint32_t stream_id, int errnum)
+void h2o_http2_encode_rst_stream_frame_(h2o_buffer_t **buf, uint32_t stream_id, int errnum)
 {
     uint8_t *dst = allocate_frame(buf, 4, H2O_HTTP2_FRAME_TYPE_RST_STREAM, 0, stream_id);
     dst = h2o_http2_encode32u(dst, errnum);
```

**Comment by kazuho** [comment]
Thank you for the fix!

**Comment by kazuho** [comment]
@deweerdt 
> We could maybe catch those at compile time with something like:

Brilliant! I had always thought that such kind of thing was impossible in C.

Maybe we should generalize the feature as a static assertion, much like `static_assert` found in C++11 and later?

Also, google led me to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=39462#c1, and that makes be believe that using a function prototype with `__attribute__(error(...))` might be a better way to display a meaningful error.

**Comment by deweerdt** [comment]
Mmm, I'm not sure how the attribute trick can work. I'm getting a warning for every time the file is included:

**Comment by deweerdt** [comment]
> Maybe we should generalize the feature as a static assertion, much like static_assert found in C++11 and later?
Yes, that was the idea. C11 even has `_Static_assert`, but unfortunately, that doesn't work because gcc evaluates this *before* it knows if `errnum` is constant. So that leads to:
```
/home/def/p/floss/h2o/include/h2o/http2_internal.h:242:59: error: expression in static assertion is not constant
     _Static_assert(__builtin_constant_p(errnum)?errnum > 0:1, "errnum must be positive"); \
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Comment by kazuho** [comment]
@deweerdt Thank you for the clarification.

So is my understanding true that you are proposing for an assertion that _optionally_ reports an error at compile time?

Assuming my understanding is correct, that sounds like a very nice thing to have (possibly named as `H2O_ASSERT`?).

**Comment by deweerdt** [comment]
> So is my understanding true that you are proposing for an assertion that optionally reports an error at compile time?

Yes, that is correct. The linux kernel uses that macro for build time assertions.

> Assuming my understanding is correct, that sounds like a very nice thing to have (possibly named as H2O_ASSERT?).

Sure. How about `H2O_BUILD_ASSERT`? It makes it clear that the check is only done at build time.

**Comment by deweerdt** [comment]
I've opened #1041 for the build time assertion thing.

**Pull request merged**
