### PR TITLE
Run git submodule update by cmake

### PR DESCRIPTION
**Pull request by uk-ar**
To simplify the workflow and reduce human errors, I propose to run the git submodule update command by CMake.

### CODE REVIEW

**Comment by uk-ar** [comment]
Thanks for the reply.

Sorry. I didn't take such usage into account. However, I was hoping to save people who are building for the first time from forgetting the git submodule update, as it is a little hard to notice the cause. To make this work, for example, we could check for the existence of ```deps/picotls/cmake/dtrace-utils.cmake``` and run git submodule update only if it doesn't exist, or output a message asking for git submodule update.
What do you think about this?

**Comment by kazuho** [comment]
Yeah. I appreciate your efforts to help newcomers. However I think this as an issue with Git in general. I'm not sure if us trying to be helpful would be worth the effort in the bigger picture.

Maybe what we need to do is instruct the users to use `git clone --recurse-submodules`. That does not break the principle of the build tool not touching the source tree, and also helps the users learn how to use Git correctly.

**Comment by uk-ar** [comment]
Thank you for sharing your thoughts. I think part of the reason is that C can't have a standard package management system. Some projects rely on packages in the system, others try to resolve dependencies with git submodule or CMake. 
Anyway, I respect the principle. We seem to have the following options, what do you think?

1. Add a note to README.md or the Wiki to use ```git clone --recurse-submodules ```.
2. output a message to ```git submodule update --init --recursive``` if you try to build without a git submodule
3. Both 1 and 2
4. Do nothing

If your choice is 1 or 2 or 3, I'll work on it; if it's 4, I'll take this PR down, so please let me know.

**Comment by kazuho** [comment]
Thanks, in 08b07d2 I've added the statement to install.mt (which in turn becomes https://h2o.examp1e.net/install.html). The page linked has not been replaced with the new one yet, I'll do that in a day or two.

**Comment by uk-ar** [comment]
Sorry for the late reply. Thank you for fixing the documentation! I checked both the page you linked and the "make doc". Now that the problem is solved, I will withdraw this MR. Thank you very much for your help.

**Pull request closed without merging**
