### PR TITLE
[proxy] Forward the `server:` header if present

### PR DESCRIPTION
**Pull request by deweerdt**
Looking at https://tools.ietf.org/html/rfc7231#section-7.4.2 I couldn't find a rationale that makes the header explicitly one hop. OTOH, forwarding the header if present does help with interop. Please let me know if you'd prefer a knob to make this configurable.

### CODE REVIEW

**Comment by kazuho** [comment]
@deweerdt Thank you for the PR.

> Looking at https://tools.ietf.org/html/rfc7231#section-7.4.2 I couldn't find a rationale that makes the header explicitly one hop.

As specified in the section, a server header is used to indicate the origin server being used. So it is appropriate to set `h2o` as the value of the header.

H2O is a content server or a gateway (a.k.a. reverse proxy). Note that in both case, the server is an _origin server_ in terms of HTTP. Quoting from [RFC 7230 section 2.3](https://tools.ietf.org/html/rfc7230#section-2.3):
> A "gateway" (a.k.a. "reverse proxy") is an intermediary that acts as an origin server for the outbound connection but translates received requests and forwards them inbound to another server or servers. Gateways are often used to encapsulate legacy or untrusted information services, to improve server performance through "accelerator" caching, and to enable partitioning or load balancing of HTTP services across multiple machines.

Regarding interop, the value of the header has historically being used to blacklisting buggy peers. So transferring the server header sent by the content server might cause issues. But there could be benefits in transferring the value set by the content server. I would appreciate it if you could clarify what you have in your mind.

**Comment by kazuho** [comment]
PS. all in all, I think that having a knob is not a bad thing. However I believe that the default should be to drop the value sent by the content server, and that the code should make sure that multiple `server` headers are not emitted when [send-server-name](https://h2o.examp1e.net/configure/base_directives.html#send-server-name) is set to `ON`.

**Comment by deweerdt** [comment]
@kazuho thank you for your comments. 0ddd57a makes this change an option controlled by a new `preserve` value that can be set to `send-server-name`. I've also rebased the branch on current master + added test coverage

**Comment by kazuho** [comment]
Thank you for the changes! Merged to master.

**Pull request merged**
