### PR TITLE
Channel notify method error handling

### PR DESCRIPTION
**Pull request by deweerdt**

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

Is this PR based on your observation that we have a code path that reaches this function without the context variable being non-NULL?

**Comment by deweerdt** [comment]
@kazuho this is the same observation by coverity as for `EVP_EncryptInit_ex` most of the other cases in the code base check for the error return. If it's impossible in this case -- i don't know about mruby to understand if this can be an issue, we should close this PR.

**Comment by kazuho** [comment]
Thank you for the clarification. I'll defer the decision to @i110. I believe that we have other parts of code that depend on `mrb_data_check_get_ptr`, and that we should have a consistent coding pattern assuming that the type of the object being passed to the caller of the get_ptr function is known to be of the correct type.

**Comment by i110** [comment]
I guess there's no chance to have this `ctx` be NULL, but as you know Ruby lets us various magics, so I think we should handle errors in any cases. Then, here we should rather use `mrb_data_get_ptr` that does that error checks and raises an TypeError in irregular cases. At least, we must not return the error object (it has no effect here)

**Comment by i110** [comment]
I filed https://github.com/h2o/h2o/pull/1794, so close this. @deweerdt Thank you for finding the issue!

**Pull request closed without merging**
