### PR TITLE
clean up a few dead stores

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
hmm... was able to pass all of the tests locally.  How do I run individual tests?

**Comment by kazuho** [comment]
Thank you for the PR.  LGTM.

The test failures in t/50reverse-proxy.t seems is happening in the master branch as well (it may be or may not be a multi-threading issue).  I am looking into it.

BTW, did you use some kind of tool to detect dead stores?

**Comment by nickdesaulniers** [comment]
Yep, I'm using clang's static analyzer.  Going to submit a patch that handles a couple of NULL checks too!

**Comment by kazuho** [comment]
In a5e692c cherry-picked the changes to file.c.

**Comment by nickdesaulniers** [comment]
I think this PR can be closed, since we cherry picked the good parts?

**Comment by kazuho** [comment]
Yeah.  closing the issue.

**Pull request closed without merging**
