### PR TITLE
add `stash` directive to store reusable yaml variables

### PR DESCRIPTION
**Pull request by i110**
https://github.com/h2o/h2o/issues/1738

### CODE REVIEW

**Comment by kazuho** [comment]
LGTM. Please merge after CI passes.

**Comment by proyb6** [comment]
I have the same issue and  would be ideal if I could split different domain name into different configuration files.

**Comment by kazuho** [comment]
@proyb6 FWIW you can load files by using "!file" https://h2o.examp1e.net/configure/syntax_and_structure.html

**Comment by proyb6** [comment]
@kazuho Thanks! I've got it working which wasn't working due previously due to misunderstanding.

**Pull request merged**
