### PR TITLE
send TLS alert before closing the socket, when OpenSSL is used and certificate verification fails (alternative to #2910)

### PR DESCRIPTION
**Pull request by kazuho**
This is an alternative to #2910.

For the description of the problem and discussion, see #2910.

### CODE REVIEW

**Review by robguima — APPROVED** [review]
lgtm thanks!

**Comment by kazuho** [comment]
@robguima Thank you for the review. Let's go with this PR.

**Comment by robguima** [comment]
great stuff! Sorry, forgot to mention that I did test this PR against the failing MTLS CI and it does seem to fix the issue.

**Comment by kazuho** [comment]
Thank you for confirming that!

**Pull request merged**
