### PR TITLE
h2olog: quote pointer addresses in JSON

### PR DESCRIPTION
**Pull request by gfx**
Amends https://github.com/h2o/h2o/pull/2562

### CODE REVIEW

**Comment by kazuho** [comment]
Elaborate why? 64-bit addresses have their MSB set to zero, so we can assume that the numbers can be represented using IEEE 754 double.

**Comment by gfx** [comment]
That's because hexadecimal literals are not permitted in JSON. I've found this in merging `master` in https://github.com/h2o/h2o/pull/2520

**Comment by kazuho** [comment]
Oh I did not realize that, but I believe it's better to emit numbers as numbers than quoting them as strings?

**Comment by gfx** [comment]
Like this? 8e59d9ea4

**Comment by kazuho** [comment]
Thank you for the changes. LGTM.

**Pull request merged**
