### PR TITLE
prometheus middleware

### PR DESCRIPTION
**Pull request by i110**
Rewrites https://github.com/h2o/h2o/pull/1831 using mruby middleware.

an example usage from updated doc:

```
listen: 8080
hosts:
  "*":
    paths:
      /metrics:
        - mruby.handler: |
            require "prometheus.rb"
            H2O::Prometheus.new(H2O.next)
        - status: ON
    access-log: /dev/stdout
```

### CODE REVIEW

**Comment by i110** [comment]
NOTE: while working on this, I feel I want to move `type` keys from c code to prometheus.rb because, if I understand correctly, `type`s are actually expressing the type of kinda ~appearance~ and they depend on the consumer of JSON data (in this case: prometheus).
So how about do like the following in prometheus.rb?

```ruby
(snip)
      keys.each { |k,v|
        type = if k =~ /\Auptime|connections|num-sessions\z/
          'gauge'
        elsif k =~ /-[0-9]+\z/
          'gauge'
        else
          'counter'
        end

        s += "#HELP #{k}\n"
        s += "#TYPE #{k} #{type}\n"
        s += "#{k}{version=\"#{version}\"} #{v}\n"
      }
(snip)
```

**Comment by kazuho** [comment]
This looks awesome.

The mruby script acts as a wrapper ("middleware" in terms of Rack), removing the need to use HTTP in order to fetch the status information from another handler.

@deweerdt Would you mind reviewing the PR?

**Comment by deweerdt** [comment]
@i110 thanks! This is a nice improvement. I'm not sure how i feel about the type being derived from the appearance. It does work for now, and skipping the C part of the PR is an advantage. On the other hand, whether a stat is a counter or a gauge is something that the consumer can't tell, so we'll have to be cognizant of this when adding new counters.

Thanks again :) LGTM.

**Comment by kazuho** [comment]
@deweerdt Thank you for the review.

> I'm not sure how i feel about the type being derived from the appearance. It does work for now, and skipping the C part of the PR is an advantage. On the other hand, whether a stat is a counter or a gauge is something that the consumer can't tell, so we'll have to be cognizant of this when adding new counters.

My view is that generally speaking "deriving type from appearance" is the correct thing to do. Consider `time_t`. It's better than using `int` because it represents the semantics of the value.

Having that said, to me the questions seems to be if we would be fine with using a naming convention that is capable of distinguishing between gauges and other types (welcome to the world of Hungarian notation!), or if we need to associate the "types" as attributes. I do not have a strong opinion on the matter.

**Comment by i110** [comment]
I pushed https://github.com/h2o/h2o/pull/1892/commits/0035ed9d5d220f04448e532b3fd643a449dacf9c, which does type-related things in mruby script, and also make some changes regarding the doc: https://prometheus.io/docs/instrumenting/writing_exporters (e.g. sanitizing the keys, removing not numeric fields, etc)

**Comment by deweerdt** [comment]
> Having that said, to me the questions seems to be if we would be fine with using a naming convention that is capable of distinguishing between gauges and other types (welcome to the world of Hungarian notation!), or if we need to associate the "types" as attributes. I do not have a strong opinion on the matter.

Yes, agreed. I think the approach take here is good.

**Comment by i110** [comment]
For record:
kazuho and me discussed, and reached to the conclusion that the current approach (https://github.com/h2o/h2o/pull/1892/commits/0035ed9d5d220f04448e532b3fd643a449dacf9c) is good because it decouples prometheus specific concepts from status JSON. Even if the concepts like  `count`, `gauge` and others are widely used there's no guarantees in the future that all metrics in status JSON can be classified in those types: they are designed for prometheus, not for h2o. The above commit encapsulates prometheus things in `prometheus.rb` that is nice layering.

@kazuho @deweerdt thank you for discussing with me. I think this PR is ready for merge if you have no concerns

**Pull request merged**
