### PR TITLE
remove a custom bpftrace from the ubuntu 20.04 image

### PR DESCRIPTION
**Pull request by gfx**
IIRC the packages related to LLVM and clang are required to build bpftrace, so they are removed as well. 

`libbpfcc-dev` is still required to build h2olog.

### CODE REVIEW

**Comment by kazuho** [comment]
@gfx Thank you for the PR, looks good. Do we want to rename the CI label ("DTrace + ASan") now that we are removing bpftrace from Ubuntu 20.04 image?

**Comment by gfx** [comment]
@kazuho Done! I'd like to update the docker image after your approval.

**Comment by kazuho** [comment]
@gfx Thank you for the cleanup, sorry for the delay. Please go ahead.

**Comment by gfx** [comment]
Updated `h2oserver/h2o-ci:ubuntu2004` and re-run CI.

**Comment by gfx** [comment]
All green ✅

**Comment by kazuho** [comment]
Cool! Thank you.

**Pull request merged**
