### PR TITLE
Fix 3 logic errors caught by static analysis #107

### PR DESCRIPTION
**Pull request by nickdesaulniers**
These should really be checked to make sure that this is the correct form of error handling.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

`h2o_mem_alloc` never returns `NULL`, as it calls `h2o_fatal` (which calls `abort(3)`) in case memory allocation fails.

Adding `__attribute__((noreturn)__` to the declaration (which should only be set for GCC and compatible compilers) of `h2o_fatal` might solve the problem.

**Comment by nickdesaulniers** [comment]
should `h2o_mem_alloc` also be marked as `returns_nonnull` then? https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html#Function-Attributes

I'll file a bug with the static analyzer.

**Comment by kazuho** [comment]
> should h2o_mem_alloc also be marked as returns_nonnull as well?

Sounds fine to me.  It would be great if you could use preprocessor macros so that use of the attribute will not cause compile errors / warnings on other compilers / older versions of GCC.

It might be worth to consider to create a `#define` named `H2O_FUNCATTR_RETURNS_NONNULL` that is either empty or `__attribute__((returns_nonnull))` depending on the compiler.

**Comment by nickdesaulniers** [comment]
Looks like [this](http://unixwiz.net/techtips/gnu-c-attributes.html#compat) will help.  I'm not sure how to see what version of GCC to check for whether noreturn is available.  Also, I thought clang on osx/bsd had a gcc front end or something; I took that to mean compatibility with gcc specific things, like the atomics I added in #98 #100 ?

**Comment by kazuho** [comment]
Thank you for looking into the issue.

* GCC version number can be checked by looking at the predefined macros in a certain way, like https://www.redhat.com/archives/libvir-list/2013-December/msg01332.html
* clang has a similar set of predefined macros that can be used for checking the interface version
* to assert that the compiler is GCC you should use `defined(__GNUC__) && ! defined(__clang__)`.
* with GCC and clang, it is possible to dump a list of a list of predefined macros by running `$CC -dM -E - < /dev/null`
* it is a good practice to declare function attributes _before_ the function declaration (e.g. `H2O_NORETURN void h2o_fatal(void);`) in order to maintain compatibility with MSVC
 * in this example `H2O_NORETURN` is the preprocessor macro to be conditionally declared as `__attribute__((noreturn))` on the platforms that support the attribute

Please feel free to ask if you need help.

**Comment by nickdesaulniers** [comment]
closing in favor of #113

**Pull request closed without merging**
