### PR TITLE
Workaround for openssl 1.1 on memcached/redis session cache resumption

### PR DESCRIPTION
**Pull request by zlm2012**
A issue was found when building h2o with OpenSSL 1.1.0f where memcached/redis session cache resumption would fail. The cause has been found hence here's a workaround.

In function `ssl_get_prev_session()` in OpenSSL, a really weird block of codes cause this problem. If we don't disable internal session cache store and return a session from our session get callback, OpenSSL will try to add the external session to internal store but expecting failure, saying if `SSL_CTX_add_session()` return 1, things are very strange. For version <= 1.0.2, no check for the function calling so there was no issue. But from 1.1.0, the function return is checked then caused session cache resumption failed with external store.

TBH I'm not so familiar with OpenSSL but the logic described above looks really strange to me.

### CODE REVIEW

**Comment by deweerdt** [comment]
@zlm2012 I believe that the bug happens because H2O is not setting the correct mode for `SSL_CTX_set_session_cache_mode` when setting up the cache for redis or memcache, it should set the `SSL_SESS_CACHE_NO_INTERNAL` flag.

**Comment by zlm2012** [comment]
I'm not pretty sure about that so just attempted to place a workaround here. Either setting SSL_SESS_CACHE_NO_INTERNAL_STORE when setting up ssl_ctx or this workaround can settle this issue. IMHO if there's no requirement that we must disable internal cache here, we could set the session in internal cache so we don't need to check redis/memcached again, unless there's any security issues. I'm not familiar with writing with OpenSSL so this is just an attempt.

**Comment by deweerdt** [comment]
> IMHO if there's no requirement that we must disable internal cache here, we could set the session in internal cache so we don't need to check redis/memcached again, unless there's any security issues

That's a fair point. We should in fact be passing `SSL_SESS_CACHE_NO_INTERNAL_STORE` (instead of my suggestion of `SSL_SESS_CACHE_NO_INTERNAL`) to `SSL_CTX_set_session_cache_mode`. That takes both care of the bug, and still uses the internal cache.

**Comment by zlm2012** [comment]
After some tracing back on code of OpenSSL, I found the logic is highly suspicious since that "things are very strange" comment is far back to the very first commit of OpenSSL when forking from SSLeay. It could be strange at that time but things could have changed. And of course due to that comment the return value of `SSL_CTX_add_session()` is checked now and cause the issue. Let me do some further investigation.

**Comment by kazuho** [comment]
I agree with @zlm2012 that we should use internal cache as a first-level cache and memcached / redis as a secondary.

> That's a fair point. We should in fact be passing `SSL_SESS_CACHE_NO_INTERNAL_STORE` (instead of my suggestion of `SSL_SESS_CACHE_NO_INTERNAL`) to `SSL_CTX_set_session_cache_mode`. That takes both care of the bug, and still uses the internal cache.

I am not sure if that is true. The man page states as follows (emphasis mine).

> Depending on the presence of SSL_SESS_CACHE_CLIENT and/or SSL_SESS_CACHE_SERVER, sessions negotiated in an SSL/TLS handshake may be cached for possible reuse. Normally a new session is added to the internal cache as well as any external session caching (callback) that is configured for the SSL_CTX. __This flag will prevent sessions being stored in the internal cache__ (though the application can add them manually using SSL_CTX_add_session). Note: in any SSL/TLS servers where external caching is configured, any successful session lookups in the external cache (ie. for session-resume requests) would normally be copied into the local cache before processing continues - __this flag prevents these additions to the internal cache as well__.
> https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_session_cache_mode.html

**Comment by zlm2012** [comment]
Actually I believe that's a bug of OpenSSL. At the very first commit where importing old SSLeay release, the comment "The following should not return 1, otherwise, things are very strange" was there, mentioning `SSL_CTX_add_session()` should not return 1. While here's something from the documentation at that commit (https://github.com/openssl/openssl/blob/d02b48c63a58ea4367a0e905979f140b7d090f86/doc/session.doc):

> int    SSL_CTX_add_session(SSL_CTX *s, SSL_SESSION *c);
SSL_CTX_add_session() returns 1 if the session was already in the cache (so it
was not added).

which is actually reversed (i.e. returns 0 if the session was already in the cache) to the implementation, even at that commit. Though the readme file for documentation at that commit said it was the old 0.6.6 documentation, where OpenSSL was based on version 0.8.1b, I believe that's the origin of that strange comment. Here's the reason:

In function `ssl_get_prev_session()`, `get_session_cb` is only called when no cached session can be found from internal cache. Then `SSL_CTX_add_session()` is called when `get_session_cb` returned a session instead of `NULL`. Then "things are very strange" if the identical session was already in the cache since it was not found before calling `get_session_cb`, in other words, `SSL_CTX_add_session()` returns 1 according to the old documentation.

This bug was not appeared since the returned value of `SSL_CTX_add_session()` was not checked. And after someone add return value checking according to that comment (fortunately, that only influenced version >= 1.1.0), it appears.

I'm preparing to try to file a PR to OpenSSL to address this problem.

**Comment by kazuho** [comment]
> I'm preparing to try to file a PR to OpenSSL to address this problem.

:+1: Sounds like the best way to fix the issue (and/or clarify how we should address the issue).

**Comment by zlm2012** [comment]
PR for OpenSSL is filed: https://github.com/openssl/openssl/pull/4014

For existed 1.1.0 version, I'm not sure if this workaround should be remained. If the PR above is accepted, everything should goes right then.

**Comment by deweerdt** [comment]
> > That's a fair point. We should in fact be passing SSL_SESS_CACHE_NO_INTERNAL_STORE (instead of my suggestion of SSL_SESS_CACHE_NO_INTERNAL) to SSL_CTX_set_session_cache_mode. That takes both care of the bug, and still uses the internal cache.

> I am not sure if that is true. The man page states as follows (emphasis mine).

Mmm, yes, i misunderstood the code, my bad. Sorry about the noise.

**Comment by zlm2012** [comment]
https://github.com/openssl/openssl/pull/4014 has been merged on both master and 1.1.0 branch. The problem should be solved when 1.1.0g released. This PR could be closed but I think there should be some caution about this issue when compiling with 1.1.0 <= version <= 1.1.0f so leaved open for now.

**Comment by kazuho** [comment]
@zlm2012 Thank you for working on the fix in upstream.

> This PR could be closed but I think there should be some caution about this issue when compiling with 1.1.0 <= version <= 1.1.0f

I agree. Would you be interested in filing a new PR that adds such warning to our documentation?

**Comment by zlm2012** [comment]
Sure! But I'm not sure where I should put the warning. Any suggestions?

**Comment by kazuho** [comment]
I believe that the warning should be inserted to the part that discusses the `memcahed` option. So how about adding a simple note at https://github.com/h2o/h2o/blob/master/srcdoc/configure/base_directives.mt#L544?

**Comment by zlm2012** [comment]
Sounds good. I'll do that. BTW I think doc `cache-store` should be updated, since we already have redis support. Feel free to close this PR.

**Comment by zlm2012** [comment]
Close with #1391 filed.

**Pull request closed without merging**
