### PR TITLE
[httpclient] Allow authority overrides

### PR DESCRIPTION
**Pull request by deweerdt**
It is sometimes handy to be able to override the authority passed to the server

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR. I agree about the usefulness, though I am a bit reluctant to have this next to `-x`. As we know, `-x` is an existing option to set authority, as well as setting the method to CONNECT.

If we are to adopt something like being proposed in this PR, I wonder if we could get rid of `-x` splitting it to an option that specifies the authority, using `-m CONNECT` as a knob to set how the established request-response stream should be used.

Separately, there's question regarding what the semantics should be. Should the new option specify the true authority? Or should the new option specify the connect address instead? I am slightly leaning towards the latter.

**Comment by deweerdt** [comment]
> Thank you for the PR. I agree about the usefulness, though I am a bit reluctant to have this next to `-x`. As we know, `-x` is an existing option to set authority, as well as setting the method to CONNECT.
> 
> If we are to adopt something like being proposed in this PR, I wonder if we could get rid of `-x` splitting it to an option that specifies the authority, using `-m CONNECT` as a knob to set how the established request-response stream should be used.
> 

That's a good point, i hesitated addressing this.

> Separately, there's question regarding what the semantics should be. Should the new option specify the true authority? Or should the new option specify the connect address instead? I am slightly leaning towards the latter.

I'm not sure. I went with overriding the true authority because that's how other clients i know tend to do it:
`curl -Hhost:www.example.com https://127.0.0.1` or `h2load -H:authority:www.example.com https://127.0.0.1` . Maybe we could go that route, and inspect whether `host:` or `:authority:` were passed via `-H`?

**Comment by kazuho** [comment]
@deweerdt At least curl has things like `-x`, `--resolve`, `--connect-to` that can be used to send requests to different locations. Alt-Svc (RFC 7838) is another example that specifies an alternative remote address.

Or to put differently, maybe we can think of request URIs as a concept at HTTP semantic layer, while remote address is a concept at the transport layer. IMO, that's cleaner than having a way to hack the semantics of HTTP.

**Comment by deweerdt** [comment]
That sounds good to me, thank you. Let's use `-x` and have `CONNECT` and `CONNECT-UDP` specified via `-m`. I can take a stab at that.

**Comment by robguima** [comment]
Just dropping a note (for posterity) as a reminder that `-A` is missing from the description in `-h` (had mentioned this to @deweerdt).

**Comment by deweerdt** [comment]
closing this in favor of https://github.com/h2o/h2o/pull/2691

**Pull request closed without merging**
