### PR TITLE
Compile error on Linux when using pkg-config

### PR DESCRIPTION
**Pull request by deweerdt**
Use CMAKE_INSTALL_LIBDIR instead of 'lib', since on linux the libraries
are installed under PREFIX/lib64

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

Seems like that CMAKE_INSTALL_LIBDIR occasionally becomes absolute path. Would it be possible to make adjustments for such case? (or is such behavior something of the past?)
ref: https://bugzilla.redhat.com/show_bug.cgi?id=795542

**Comment by deweerdt** [comment]
@kazuho thanks for your comment. I've adapted the PR to take that case into account by using `GET_FILENAME_COMPONENT`. That function is available since cmake 2.6.

**Comment by deweerdt** [comment]
Added a fix for v2.8, which treats empty variables slightly differently in 62d8fee

**Comment by kazuho** [comment]
Thank you for the updates.

Could we use CMAKE_INSTALL_FULL_LIBDIR instead? The directive seems to be available since earlier than 2.8.11 (see https://cmake.org/Wiki/CMake_2.8.11_Docs).

The reason I suggest this is because the current approach (using `basename`) would fail when libdir is not a sibling of bindir.

**Comment by deweerdt** [comment]
Thanks for the idea, @kazuho. I've updated the code to use CMAKE_INSTALL_FULL_LIBDIR, it's available since 2.8.10 according to the cmake git repo.

**Comment by kazuho** [comment]
Thank you for the fix and for checking the availability.

**Pull request merged**
