### PR TITLE
mruby: support env[rack.input]

### PR DESCRIPTION
**Pull request by takahashim**
I made a patch to support `rack.input` on rack-based API.

`rack.input` is IO-like object to use request body. (see http://www.rubydoc.info/github/rack/rack/file/SPEC#The_Input_Stream )
In CRuby, `rack.input` is usually an StringIO object.  There is a StringIO gem in mruby (https://github.com/ksss/mruby-stringio), but Input Stream does not need much methods and does need speed, so I made new mrbgem mruby-input-stream.

### CODE REVIEW

**Comment by takahashim** [comment]
There's a conflict of this PR, so I've rebased.

**Comment by kazuho** [comment]
Thank you for the PR.  It is interesting to know that doing this kind of thing in C results in less execution time.  I had anticipated that the overhead of going to and from mruby to C was heavier.

That said, I have couple of concerns regarding the pull-request.  The biggest issue is that it is impossible to handle binary input.

My understanding is that the Rack specification recommends providing binary input to applications.  However, mruby-input-stream provides access only to input decoded as UTF-8 (note: mruby-string-utf8 is activated in mruby bundled bundled by H2O).

I could accept a PR without support for binary, but IMO the API should be forward-compatible against future versions (possibly) with binary support.

Do you have any suggestions?  Personally I would like to resolve this design issue before going on to the technical details on how to implement the input stream.

**Comment by takahashim** [comment]
Thanks for your comment!
Yes, original Rack spec need "ASCII-8BIT" as return value of input stream.
But unlink CRuby, mruby doesn't have any Encoding (cf. https://github.com/mruby/mruby/issues/1715#issuecomment-35236786),
and ByteString (ByteArray) class is not recommended. (cf. https://github.com/mruby/mruby/issues/1715#issuecomment-35345222)

(Note: even with mruby-string-utf8, there's no `String#valid_encoding?` method. You can store any binary data in String without warnings.)

AFAIK there's no official policy of string encodings in mruby, but IMHO current best practices are: 

* When you want to use only binary data, use String without mruby-string-utf8.
* When you want to use only UTF-8 string, use String with mruby-string-utf8.
* When you want to use UTF-8 data and binary data, use String for both with mruby-string-utf8.
    * When you want to use String as binary data, use byte-oriented methods.
* When you want to use other encodings, convert one into UTF-8.

And now we can use many byte-oriented String methods in mruby:

* String#bytesize
* String#bytes
* String#getbyte  (in mruby-string-ext mrbgem)
* String#setbyte  (in mruby-string-ext mrbgem)
* String#byteslice  (in mruby-string-ext mrbgem)

So even when String is defined as UTF-8, we can use String object as return value of input stream of Rack, I guess. (In other words, I guess I should not define new class for the return value of input stream.)

One point I worry about is that we cannot define binary (ASCII-8BIT) mode in Regexp.
ISO Ruby doesn't have one, and in mruby-onig-regexp encoding is hard-coded as UTF-8.
IMO we need `n` option (like `/foo./n`) in Regexp literal or encoding option
in Regexp#new (like `Regexp.new("foo.", nil, encoding: "binary")`).
But I think the former is not recommended in CRuby after 1.9 era (use `Regexp.new("foo.".encode("binary"))`), the latter is not compatible with CRuby.

**Comment by jodosha** [comment]
:100: :sparkles:

**Comment by kazuho** [comment]
@takahashim Thank you for the analysis.

Reading your comment, it sounds like we should store the input in String even if it is binary.  And the regexp issue sounds like something that need to be handled within mruby-onig-regexp (or by the mruby core).

**Comment by kazuho** [comment]
Onto the topic how we should implement `rack.input`, I have taken a simple benchmark using InputStream and StringIO, and I agree that StringIO is slow.  OTOH I do not think we should necessary use C-backed class for handling the input.

The below chart includes the benchmark I conducted, with the _pure_ row being the score of https://gist.github.com/kazuho/054292a327692a3ae942.

implementation | performance (reqs./sec.) |
------------------ | -----------: |
inputstream | 1,533K |
stringio | 201K |
pure | 716K |

As you can see, it is possible to achieve more than 700K reqs. per second using ruby-based implementation (note: as a comparison, H2O can at most reach 300K reqs. per second with the file handler handling GET requests).

Considering the downside of using C-backed interface (it is not only harder to maintain but also harder to extend at the ruby-side), to me it seems it is not worthwhile to use C-backed interface in this case (I am sorry to say this after you have spent time of implementing it).

(FWIW, I am considering of providing a way to load mruby scripts that is shared server-wide so that it would be easier for users to share the logic between the handlers defined using `mruby.handler` directives)

**Comment by takahashim** [comment]
Good benchmark!
I have no objection using pure ruby version.  I also think that pure Ruby is better than C for maintenance if speed is not a problem.

I am concerned about difference of APIs between original Rack and mruby rack based API.  If we can use `env["rack.input"]` to get request body, I don't mind anymore.

**Comment by kazuho** [comment]
Finally I have merged your work in #638.  Thank you very much for your contribution and patience!

**Pull request merged**
