### PR TITLE
it would be ideal if we did not need to use -c flag to a particular

### PR DESCRIPTION
**Pull request by devnexen**
configuration location, thus a new cmake variable.

Reasoning behind is tried to package it for a particular system and would be preferable not using c flag while the configuration path would be known at compilation time.

hope it is useful.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

I agree that it would be better to have a default location for `h2o.conf`.
I also believe that the default path should be set to the appropriate directory of most distributions.

@dch @tatsushid
Where do you store `h2o.conf`? Is it stored below the `etc` directory of the installation target directory?

**Comment by tatsushid** [comment]
In my RPM package case, I put `h2o.conf` file in `/etc/h2o` directory like many distributions' Apache (`/etc/httpd`, `/etc/apache` etc.) and NGINX (`/etc/nginx`) configuration.

**Comment by devnexen** [comment]
I have two particular cases /etc/h2o like @tatsushid and another one /usr/local/etc/h2o

**Comment by kazuho** [comment]
@tatsushid @devnexen Thank you for your answer, and sorry for the delay.

Considering all of this, I _think_ we should:
* use [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) for locating various directories (e.g. bin, lib, share/doc/h2o, etc)
* default path of the configuration path should be `%sysconfdir%/h2o.conf`

By doing so, users can override the configuration directory by specifying `CMAKE_INSTALL_SYSCONFDIR`.

Note that with the method proposed in this comment, the default path for `h2o.conf` would be `/usr/local/etc/h2o.conf`, without `h2o` subdirectory beneath `etc`.

This might seem inconvenient, but my understanding is that it is the conversion (please see  www.linuxfromscratch.org/blfs/view/7.7/postlfs/openssh.html for an example).

**Comment by devnexen** [comment]
Thanks for your input and suggestions ! I ll try to come up with a newer version later on.

**Comment by kazuho** [comment]
@devnexen Thank you for updating the PR, and sorry for the delay.

The changes look good to me; I will resolve the conflict on my side and merge this PR.

**Comment by devnexen** [comment]
No problems I understand, I fixed the conflict anyway.

**Comment by kazuho** [comment]
Thank you for doing it! Merged to master.

**Comment by dch** [comment]
late reply but we use `/usr/local/etc/h2o/h2o.conf` on FreeBSD by default. This makes it esay to set up the directory permissions correctly in the port, and is handy for stashing htpasswd and similar files under it.

**Pull request merged**
