### PR TITLE
[cmake] Versions of libbrotli > 0.5 include a 'common' library

### PR DESCRIPTION
**Pull request by deweerdt**
We adapt CMakeLists.txt to handle the case where libbrotli has a libbrotlicommon library.

https://github.com/google/brotli/blob/master/CHANGELOG.md#050---2016-06-15

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

Am I correct to understand that your problem is with building a static libh2o (rather than a dynamically linked one)?

I wonder if this would be the correct solution, at least on Ubuntu 22.04, considering that pkg-config correctly identifies libbrotlicommon as one of the dependencies when given the `--static` option.

```
$ pkg-config --libs --static libbrotlienc
-lbrotlienc -lbrotlicommon 
```

**Comment by deweerdt** [comment]
Yes, that's correct, that happens when linking to the static version (or something that links to the static version). Am i understanding correctly that you are suggesting we could use `pkg-config` to find the correct library list? That makes sense to me, let me take a stab at it.

**Comment by kazuho** [comment]
@deweerdt Thanks.

> m i understanding correctly that you are suggesting we could use `pkg-config` to find the correct library list? That makes sense to me, let me take a stab at it.

My understanding is that we already do so, as we are using `PKG_CHECK_MODULES`.

So it seems to me that we are either using the function in an incorrect way, or that the function is somehow failing to determine that we need the list of libraries to link to when building static. And why.

**Comment by kazuho** [comment]
@deweerdt 
> The following variables may be set upon return. Two sets of values exist: One for the common case (<XXX> = <prefix>) and another for the information pkg-config provides when called with the --static option (<XXX> = <prefix>_STATIC).
https://cmake.org/cmake/help/latest/module/FindPkgConfig.html

This may be what we are looking for.

**Comment by deweerdt** [comment]
@kazuho sorry about the noise, i traced the error to a faulty install on my machine. I'll close the PR.

**Pull request closed without merging**
