### PR TITLE
replace mrub-iijson with mruby-json

### PR DESCRIPTION
**Pull request by yannick**
mruby-json is 2-30 times faster, better maintained and uses a well maintained c library (parson).
it's a drop in replacement, i  did not see any features missing.

### CODE REVIEW

**Comment by kazuho** [comment]
I am generally positive to making this change.

OTOH, I have heard that mattn/mruby-json does not support pretty_print. @mattn Is that something you plan to implement (or accept a PR)?

Are there any other features that might be missing?

**Comment by mattn** [comment]
Here you are https://github.com/mattn/mruby-json/pull/22

**Comment by proyb6** [comment]
@yannick Plan to publish your benchmark chart with the actual amount of speed up in your test?

**Comment by yannick** [comment]
@proyb6 i only did a very basic benchmark, however you can also clearly see the impact in the round 15 results of https://www.techempower.com/benchmarks/ 

what i did and what you can easily reproduce is:


```1_000_000.times do
    [{:message => "Hello, World!"}.to_json]
end
```
iijson:  33.3 s
mruby-json: 1.31s

and

```#str is: https://raw.githubusercontent.com/miloyip/nativejson-benchmark/master/data/twitter.json
1000.times do 
    jsn = JSON.parse(str)
end
```

iijson: 33s
mruby-json: 16.3s

**Comment by yannick** [comment]
wow, thank you @mattn !   updated it.

**Comment by proyb6** [comment]
Great, it’s going to be great for mobile. My concern were small and large JSON data should be performant.

**Comment by yannick** [comment]
@kazuho anything left to do here?

**Comment by kazuho** [comment]
@yannick Thank you for working on this. I have essentially cherry-picked the changes in #1684.

**Comment by yannick** [comment]
Perfect thanks

**Pull request closed without merging**
