### PR TITLE
Add macros to hide/simplify vector operations and replace verbose vec…

### PR DESCRIPTION
**Pull request by mingodad**
Add macros to simplify vector operations and replace verbose vector operations with then.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR!  Looks like a great addition.

Will merge after adding some tweaks.

**Comment by kazuho** [comment]
Sorry for the delay.

Today I have been working on the PR, and found out that many macros referred to the arguments more than once - which is something we would generally want to avoid.

Therefore, I have cherry-picked by hand only the addition of `h2o_vector_reserve`.

Regarding other additions, I assume `h2o_vector_reserve_more` can be implemented without touching an argument more than once in the macro.  I doubt if the rest can be.

Do you have any suggestions?

**Comment by mingodad** [comment]
You are right I missed several misuses with side effects.
I rewrote then macros using assert to verify (at runtime) that no unexpected side effects with the macros parameters will pass unnoticed.

Another option is to write h2o in C++.
Cheers !

**Comment by mingodad** [comment]
I also found this https://gcc.gnu.org/onlinedocs/cpp/Duplication-of-Side-Effects.html and clang also accept that.
This solution is better than using "assert" although not standard.

**Comment by kazuho** [comment]
Using an assert is not an option, since it would not restrict a side-effect to be applied more than once, as shown in the following example.

```c
#define F(x) assert((x) == (x))

static int c = 0;
int foo() { ++c; return 0; }
F(foo())
```

And I am against using `typeof`.  One of the reason H2O is written in C is to maximize portability; using of an compiler-specific extension contradicts with the goal.  I think it would be better for us to just accept and live with the limitations of C rather than looking for a hack to fix the issue of the programming language.

**Comment by mingodad** [comment]
Talking about portability what about "alloca"  it's not standard also, I'm refactoring h2o to compile as C++ and tried to wrap "alloca" with a inline function "h2o_mem_alloca" and it segfaults then I used a macro "#define h2o_mem_alloca(sz) alloca(sz)" again everything went fine, but then I used this macro "#define h2o_mem_alloca(sz) h2o_mem_alloc(sz)" and althoug it worked h2o leaks all memroy allocated with it, so h2o right now only works with compilers that provides "alloca".

Cheers !

**Comment by mingodad** [comment]
On my C++ compilation I've added "h2o_mem_free_alloca" on all places that "alloca/h2o_mem_alloca" is called and could flip between "h2o_mem_alloca/h2_mem_free_alloca" and "h2_mem_alloc/h2o_mem_free" with almost the same performance.

P.S.:  On function "static int write_core(int fd, h2o_iovec_t **bufs, size_t *bufcnt)" the allocated pointer is modified so I needed to save it twice (here void do_write(h2o_socket_t *_sock, h2o_iovec_t *_bufs, size_t bufcnt, h2o_socket_cb cb)) to free the original allocation.

Cheers !

**Comment by kazuho** [comment]
@mingodad 
> Talking about portability what about "alloca" it's not standard also, I'm refactoring h2o to compile as C++ and tried to wrap "alloca" with a inline function

Thank you for your efforts.

Unfortunately, I believe that generally speaking it is a bad idea to write a a library in C++, since:
* it forbids the library from being used from C
* C++ as a language is unstable compared to C
* C++ ABI is unstable compared to C

Most part of H2O is provided as a library as well, and considering the issues, we do not plan to accept changing their language to C++.  Writing a handler that will only be used by the standalone server in C++ is acceptable, though I would suggest writing in C so that it could be part of libh2o as well.

The use of `alloca` is a performance optimization.  If there is a demand, we can change the functions to not use the function without changing the interface.  And FYI the function preserves memory _until the calling function exits_ - in other words wrapping alloca as a function never works.

**Pull request closed without merging**
