### PR TITLE
proposal for cpu affinity feature

### PR DESCRIPTION
**Pull request by devnexen**
Here a draft if and only if this feature has some interest.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

Could you please elaborate what you are trying to achieve by using the CPU affinity?

If the use-case you have in mind is to restrict the CPU cores that run H2O, I have two concerns.

* what is the merit of implementing the feature within the server instead of relying on an wrapper process (e.g. the `taskset` command) to set the affinity?
* should the affinity setting affect the value set by [num-threads](https://h2o.examp1e.net/configure/base_directives.html#num-threads)?

**Comment by devnexen** [comment]
- True this is always possible via taskset, it is just done here software wise here for conveniency.
- Good point I restricted by num threads because in a previous version I pushed the affinity possibility "threads wise" which finally I abandoned.

**Comment by kazuho** [comment]
@devnexen Thank you for the response.

> True this is always possible via taskset, it is just done here software wise here for conveniency.

If that is the case, it might be better to lead the users to use external commands instead of trying to provide such features within the server.

We can think of other properties that the user might want to set (e.g. nice), and some of them might be OS-specific.  Trying to support every such property might be bothersome.

How do you think?

**Comment by devnexen** [comment]
> We can think of other properties that the user might want to set (e.g. nice), and some of them might be OS-specific. Trying to support every such property might be bothersome.

That s true and going so far is really overkill :-) well this PR was just more a draft I knew it would trigger questioning :-)

**Pull request closed without merging**
