### PR TITLE
don't redirect (with `/` added) in core; do it in the `file.dir` handler

### PR DESCRIPTION
**Pull request by kazuho**
Still WIP.

When H2O receives a request against a path configured with `paths` directive (or by calling `h2o_config_register_path`) without a trailing slash, the server sends a 301 that redirects the client to a path with `/` added.

We have seen a few people argue against this behavior (see #711).

The behavior is also a headache; with the current design it is impossible to create a directive for per-file mapping (instead of the existing per-directory mapping) of statically-served files, which is useful for setting specific paths to certain URI paths (e.g. `robots.txt`, `favicon.ico`).
```yaml
paths:
  /favicon.ico:
    file.file: /path/to/favicon.ico
```

Considering the facts, this PR tries to move the 301 redirect from core to the handler of the `file.dir` configuration directive, thereby resolving the described two problems.

The downside of the PR is that this would be a breaking change for the standalone server - we would need to update the version number to 2.0 as well as checking that all the built-in handlers correctly handle the requests without `/` at the end.
For libh2o users, we could simply add an extra argument to `h2o_config_register_path` that lets users specify which behavior is desirable.

### CODE REVIEW

**Comment by kazuho** [comment]
The PR changes the behavior of redirect handler (and `reverse.proxy.url`) as follows:

~1.7.x:
```yaml
  /abc:
    redirect: http://example.com/def # /abc/xyz => /defxyz
  /abc:
    redirect: http://example.com/def/ # /abc/xyz => /def/xyz
  /abc/:
    redirect: http://example.com/def # /abc/xyz => /defxyz
  /abc/:
    redirect: http://example.com/def/ # /abc/xyz => /def/xyz
```

this PR:
```yaml
paths:
  /abc:
    redirect: http://example.com/def # /abc/xyz => /def/xyz
  /abc:
    redirect: http://example.com/def/ # /abc/xyz => /def/xyz
  /abc/:
    redirect: http://example.com/def # /abc/xyz => /def/xyz
  /abc/:
    redirect: http://example.com/def/ # /abc/xyz => /def/xyz
```

The change makes sense to me.  In the only difference between the two which is the third example in the current implementation, `/abc/xyz` is converted to `/defxyz` - looks pretty odd.

If we consider this behavior as a bug, then we would not need to consider this as a breaking change for the standalone server.

**Comment by utrenkner** [comment]
@kazuho 

>  In the only difference between the two which is the third example in the current implementation,

From your post it seems like the result of the first example would also change `defxyz` to `/def/xyz`. Is this correct or not?

**Comment by kazuho** [comment]
@utrenkner Thank you for pointing that out.  Updated my previous comment.

**Comment by omarkilani** [comment]
This is a really great change. :) Will solve a number of issues I'm having rewriting a large Apache config.

**Pull request merged**
