### PR TITLE
[conf] [bug-fix] failure to open pid-file should not cause h2o to exit

### PR DESCRIPTION
**Pull request by nalramli**
## Overview
Currently, failure to open `pid-file` results in the `h2o` process exiting with `EX_OSERR`.  The `pid-file` is not used for anything critical and there is no reason for this error to be fatal.  This patch changes this condition to a `warning` and continue on.

Additionally, `fopen()` may fail to open the `pid-file` if the previous run crashed and did not delete it.  This patch deletes the file on start-up before dropping privileges to ensure that the file doesn't exist before attempting to create it.

### Configuration
```
pid-file: /var/run/h2o/h2o.pid

listen:
  host: 0.0.0.0
  port: 80
listen:
  host: 0.0.0.0
  port: 443
  ssl:
    key-file: examples/h2o/server.key
    certificate-file: examples/h2o/server.crt
```

### Before the patch
```
$ sudo kill -KILL $(cat /var/run/h2o/h2o.pid)

$ sudo touch /var/run/h2o/h2o.pid

$ sudo ./h2o --conf=./h2o.conf --m worker
...
failed to open pid file:/var/run/h2o/h2o.pid:Permission denied

$
```

### After the patch
```
$ sudo ./h2o --conf=./h2o.conf --m worker
...
h2o server (pid:42956) is ready to serve requests with 2 threads

$ cat /var/run/h2o/h2o.pid
42956
```

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

>  The `pid-file` is not used for anything critical and there is no reason for this error to be fatal.

I'm not sure if I agree. While it is true that the h2o process does not use the pid file, the file having correct PID is critical for other processes dealing with h2o (e.g., sending SIGHUP, SIGTERM).

> Additionally, `fopen()` may fail to open the `pid-file` if the previous run crashed and did not delete it.

I'm also uncertain if that is the case. PID file is created after dropping the privileges. Therefore, `fopen` should be capable of reopening it. I think your experiments failed to capture this part.

**Comment by nalramli** [comment]
Thanks for your review.

> I'm not sure if I agree. While it is true that the h2o process does not use the pid file, the file having correct PID is critical for other processes dealing with h2o (e.g., sending SIGHUP, SIGTERM).

I agree that it might be critical for some other processes to rely on `pid-file`.  However, I was referring to the fact that within `h2o` itself there is nothing critical that relies on the file.  Do you think we should keep it a fatal error?  I think if this is the case then we would have to remove the configuration from our environment, at least until we understand why the file could not be opened.

> I'm also uncertain if that is the case. PID file is created after dropping the privileges. Therefore, `fopen` should be capable of reopening it. I think your experiments failed to capture this part.

This occurred in a production node, although we cannot find a root cause for why the file could not be opened.  However, I am able to reproduce a version of it as you can see in my experiment, and that is by changing the file permissions outside of `h2o`.  And in this case, the process is able to deal with it and start up successfully.

Either way, I think it is fair to attempt to delete the file on start-up, in case the process did not exit cleanly and therefore the old file still exists.  What do you think?

If you're not inclined to merge, please let me know and I would be OK to close it.

**Comment by kazuho** [comment]
> Do you think we should keep it a fatal error?

I think so. Because it has been our contract that we'd expose the PID through the file.

> I think if this is the case then we would have to remove the configuration from our environment, at least until we understand why the file could not be opened.

Or do whatever necessary with the branch you are maintaining. Assuming we agree that this is an issue with your environment, I am opposed to changing the contract that we have because of an issue in one of our users.

**Comment by nalramli** [comment]
Fair enough.  Closing in favor of patching in our local environment, until we understand the issue more.

**Pull request closed without merging**
