### PR TITLE
Use designated struct initializers

### PR DESCRIPTION
**Pull request by jbenoist**
This patch replaces Implicit initialization of some important structs with designated initializers. 

The real reason behind this is to prevent unfortunate merge or refactoring misses, but as a side benefit, this might make the code a bit more idiomatic.

### CODE REVIEW

**Comment by kazuho** [comment]
I can see the benefit, though I think it is generally a good idea to not start using new language features on a case-by-case basis, as it might break compilation on certain environments.

**Comment by gfx** [comment]
FYI CRuby comitters have decided to use part of C99 from Ruby 2.7 and published a report about it: https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/C99

**Comment by jbenoist** [comment]
> FYI CRuby comitters have decided to use part of C99 from Ruby 2.7 and published a report about it: https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/C99

Thanks Goro! Pretty interesting stuff actually. I wonder what features would be the most for h2os' code. Any idea?

**Comment by kazuho** [comment]
@gfx Thank you for sharing that.

I think we can blindly follow what cruby does, until we find some feature missing that we want to use.

But to mimic cruby, we need to figure out what exact compile options cruby is using. @gfx Do you have that info?

**Comment by gfx** [comment]
Sorry for my late response.

CRuby uses autoconf to detect C99 options [AC_PROG_CC_C99](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/C-Compiler.html): https://github.com/ruby/ruby/blob/master/configure.ac#L194

which in turn generates a shell-script snippet like this:

```sh
for ac_arg in '' -std=gnu99 -std=c99 -c99 -AC99 -D_STDC_C99= -qlanglvl=extc99
do
  CC="$ac_save_CC $ac_arg"
  if ac_fn_c_try_compile "$LINENO"; then :
  ac_cv_prog_cc_c99=$ac_arg
fi
 ```

**Comment by kazuho** [comment]
@gfx Thank you for checking. Looking at the results, I think we can start by using `-std=c99` and see what happens.

The other option is to use C_STANDARD property (https://cmake.org/cmake/help/v3.8/prop_tgt/C_STANDARD.html#prop_tgt:C_STANDARD), though I am afraid it would not work with older versions of CMake that we support.

**Comment by kazuho** [comment]
@jbenoist Thank you for the efforts. Cherry-picked in #2189. @gfx Thank you for your suggestions.

**Pull request closed without merging**
