### PR TITLE
[http2] [conf] configure streaming request count with default of 1

### PR DESCRIPTION
**Pull request by nalramli**
During a large file upload to h2o, http2 can be slower than http1.  In my test the browser will make 6 simultaneous PUT requests to upload parts of the file.  In http2 only one request is able to make progress and the 5 other are blocked, whereas in http1 all 6 connections can make progress simultaneously.  Apparently, h2o throttles http2 streaming requests to 1 per connection.  This makes it a configurable parameter with default equal to 1.

### CODE REVIEW

**Comment by nalramli** [comment]
https://jira.corp.fastly.com/browse/EP-492

**Review by kazuho — COMMENTED** [review]
Thank you for working on this.

This PR is an improvement: changing concurrency limit from a hard-coded limit of 1 to a configurable parameter.

That's fine, however, I think the default should continue to be set to 1. 

When the backend server is a HTTP/1 server that cannot handle large number of requests concurrently (think of Apache using prefork MPM, that can accept only handle one connection per process), there is a security risk in starting to forward requests to the backend before the entire request is being received by h2o (think of each HTTP/2 stream mounting a slowloris attack).

That's why we have a limit separate from HTTP/2 stream-level concurrenc limit, and the rationale for choosing 1 as the limit is to reduce the risk equivalent to that of HTTP/1: i.e. one slow request per connection.

Compared to that, I'm not sure if we have persuasive argument for changing to 6. If performance is the argument, then it should be 100 (i.e. our HTTP/2 stream-level concurrency limit). We might argue that we should balance security vs. performance, but then 6 just looks like an arbitrary number without ground.

**Comment by nalramli** [comment]
@kazuho

> Compared to that, I'm not sure if we have persuasive argument for changing to 6. If performance is the argument, then it should be 100 (i.e. our HTTP/2 stream-level concurrency limit). We might argue that we should balance security vs. performance, but then 6 just looks like an arbitrary number without ground.

Thanks for your review.  Apparently modern browsers open 6 streams when uploading, and that's why I set the default to 6.  If the back end has less capacity, then the other 5 will just be throttled and to the end user the behavior is similar.  With this in mind, I have no problem changing the default back to 1.  Please let me know what you think.

**Comment by kazuho** [comment]
> Apparently modern browsers open 6 streams when uploading, and that's why I set the default to 6. If the back end has less capacity, then the other 5 will just be throttled and to the end user the behavior is similar.

When HTTP/2 is used, web browsers would open as many streams as possible as permitted by the HTTP/2 stream-level concurrency limit that h2o advertises (which is 100). Therefore, regardless of our setting being 1 or 6, most of the requests would be blocked by h2o.

**Comment by nalramli** [comment]
In my test when uploading a large file on a specific website I saw 6 simultaneous http2 PUT requests being sent at a time.  It may be that specific web application, not a browser setting.  Perhaps more testing is required.

**Comment by kazuho** [comment]
I would appreciate it if you could change the default to 1, because as [stated previously](https://github.com/h2o/h2o/pull/2777#pullrequestreview-695514067), it comes from a security requirement. [6 is a number that has been considered to be insufficient for good performance](https://github.com/h2o/h2o/pull/2777#issuecomment-870934474), and therefore I would be hesitant to use that as a default.

**Comment by kazuho** [comment]
Thank you for the changes. Merging. Separately, as time goes, I think we'd better look into having this knob for HTTP/3 as well. But that can be left to another PR.

**Pull request merged**
