### PR TITLE
imporved error handling for setup_ecc_key().

### PR DESCRIPTION
**Pull request by cubicdaiya**
There is a lack of error-handling for `EC_KEY_new_by_curve_name()`.

### CODE REVIEW

**Comment by kazuho** [comment]
@cubicdaiya 
Thank you for the PR.

Would you mind changing the approach from exiting the program in case of error to emitting a warning and continue? ECDH is an optional cipher, websites should be allowed to operate without it.

I would also appreciate it if you could provide the details of the configuration that does not provide `NID_X9_62_prime256v1`, so that me and others can revisit the issue.

**Comment by cubicdaiya** [comment]
@kazuho 

> Would you mind changing the approach from exiting the program in case of error to emitting a warning and continuing? ECDH is an optional cipher, websites should be allowed to operate without it.

I see. 

> I would also appreciate it if you could provide the details of the configuration that does not provide NID_X9_62_prime256v1, so that me and others can revisit the issue.

Sorry for the lack of my explanation. In fact, I don't have the environment for reappearing the condition such as `NID_X9_62_prime256v1` is not provided .

On the other hand, regardless of whether it is possible to provide `NID_X9_62_prime256v1`, I think the NULL-check for `EC_KEY_new_by_curve_name()` is required. Because `EC_KEY_new_by_curve_name()` calls `malloc()` internally. (The return value of `malloc()`  should be NULL-checked always.)

**Comment by cubicdaiya** [comment]
@kazuho 

> Would you mind changing the approach from exiting the program in case of error to emitting a warning and continuing? ECDH is an optional cipher, websites should be allowed to operate without it.

I pushed the commint for changing the behavior related above. Please check again.

**Comment by kazuho** [comment]
Thank you for the changes and the explanation.  Understood and agreed. Merged to master.

**Pull request merged**
