### PR TITLE
expose server-push interface to mruby

### PR DESCRIPTION
**Pull request by kazuho**
The PR exposes `http2_server_push` property of the request object so that mruby can push things to the clients.

At the moment, only the `<<` operator is implemented.  We need to implement other operators (and methods) so that the property would behave like an ruby array.  The question is how it should be done.

relates to #421 #438.

### CODE REVIEW

**Comment by matsumoto-r** [comment]
Wow! I also believe that h2o_mruby shoud use server-push in mruby. It's great!

**Comment by kazuho** [comment]
Once #461 gets merged it would become possible to configure server-push like:
```
hosts:
  "www.example.com":
    listen:
      (snip)
    paths:
      "/":
        mruby.handler:
          r = H2O::Request.new
          if r.uri == "/"
            r.http2_push_paths << "/style.css"
          end
        file.dir: /path/to/doc-root
```

**Comment by kazuho** [comment]
FWIW, since the merger of #489 the interface has changed to:
```
hosts:
  "www.example.com":
    listen:
      (snip)
    paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
            push_paths = []
            if env["PATH_INFO"] == "/"
              push_paths << "/style.css"
            end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload"}.join()}, []]
          end
        file.dir: /path/to/doc-root
```

**Comment by valour01** [comment]
Hi
Could you please tell me how can I push more than one resource

My configure about server push here:
 paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
            push_paths = []
            if env["PATH_INFO"] == "/"
              push_paths << "/wine.css"
              push_paths << "/infocard.css"
            end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload"}.join()}, []]
          end
        file.dir: /path/to/doc-root

But I can only get one push promise for /wine.css. Do you know why? Many Thanks

**Comment by valour01** [comment]
And in my index.html the rel of the link is stylesheet. But the configure you give is proload. I don't know what does this variable mean. I changed the rel from preload to stylesheet in the configure. Then I can not get push promise

<link rel="stylesheet" href="css/infocard.css">
<link rel="stylesheet" type="text/css" href="css/wine.css" />

**Comment by kazuho** [comment]
@valour01 There was a bug in the example.  Changing `join()` to `join("\n")` should work.

Please refer to http://www.w3.org/TR/preload/ for regarding what `rel=preload` means.

**Comment by valour01** [comment]
@kazuho  Thanks. It works for me.

**Pull request merged**
