### PR TITLE
Update deps/brotli to 1.0.9.

### PR DESCRIPTION
**Pull request by omasanori**
The commits brought by this can be reviewed at https://github.com/google/brotli/compare/62194f2...v1.0.9.

### CODE REVIEW

**Comment by Fudoshiki** [comment]
Any plan to merge this?

**Comment by omasanori** [comment]
Rebased to master.
Note that **[brotli 1.0.8 was released](https://github.com/google/brotli/releases/tag/v1.0.8) today** 🎉 (I noticed that after fixing merge conflicts, which is sad, but anyway...) so I will also update this PR to 1.0.8 before merging.

**Comment by omasanori** [comment]
Due to packaging problems, 1.0.9 was released. Note that 1.0.8 (and thus 1.0.9) contain [a security fix](https://github.com/google/brotli/commit/223d80cfbec8fd346e32906c732c8ede21f0cea6).
/ping @kazuho

**Comment by omasanori** [comment]
@kazuho any opinions, please?

**Comment by omasanori** [comment]
I understand that you are really busy before IETF Meetings, but could you tell me the reasons behind postponing this update @kazuho?

**Comment by omasanori** [comment]
Rebased.

**Pull request closed without merging**
