### PR TITLE
[mruby/middleware.c] Fix invalid read on the stack

### PR DESCRIPTION
**Pull request by deweerdt**
`*((struct sockaddr_storage *)&sin);` would cause a read that's larger
than `sin`, reaching to other parts of the stack. We fix this with a
memcpy that only reads `sizeof(sin);` bytes.

### CODE REVIEW

**Comment by kazuho** [comment]
Nice catch! How about 8f27b03?

**Comment by deweerdt** [comment]
8f27b03 is even better, @kazuho. Thank you.

**Comment by deweerdt** [comment]
I've cherry picked 8f27b03 in this PR as 2bbb1ca

**Comment by kazuho** [comment]
Oh thank you for moving this forward. Please merge once the CI succeeds.

**Comment by deweerdt** [comment]
done, thank you 👍

**Pull request merged**
