### PR TITLE
[h2o_mruby] Add H2O class and simple method

### PR DESCRIPTION
**Pull request by matsumoto-r**
h2o_mruby support H2O class of mruby. For now, I implemented `H2O.max_headers` method.

```ruby
H2O.max_headers #=> 100
```

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.  The code looks good to me.

OTOH `H2O_MAX_HEADERS` is a limitation only applied to the HTTP parsers (you can add / emit any number of headers from mruby), and therefore I do not see any particular reason for exposing the value.

How about adding other features and then merging to master?

**Comment by matsumoto-r** [comment]
Thank you for your review.

> I do not see any particular reason for exposing the value.
> How about adding other features and then merging to master?

I wanted to implement a simple method of `H2O` class for now, but I feel fairly sure that `max_headers` method is impracticable. So, I try to add other practicable feature like error logging or header control.

 > Applying clang-format -i to the source files is appreciated (or you can run misc/clang-format-all.sh to indent all the files at once).

Thank you for the notice. I see!

**Comment by matsumoto-r** [comment]
@kazuho sorry for my late response. I implemented error log method and applied clang-format, but I'm not sure what to do about test of error log method. What do you think about this test?

**Comment by kazuho** [comment]
@matsumoto-r Thank you for the updates.  The code looks good to me.

> I'm not sure what to do about test of error log method. What do you think about this test?

I would not request every method to have a test.  In this case, I think we can go without having one.

**Comment by matsumoto-r** [comment]
@kazuho Thank you for your thoght. So, I had just finished the scope of this PR which include `H2O` basic class for now. Please check it.

**Comment by kazuho** [comment]
Sorry for being late.  LGTM.  Merged to master.

**Comment by matsumoto-r** [comment]
Thanks!!

**Pull request merged**
